### ISSUE TITLE
 How to set the varieble "SYNTH_ARGS"?

### ISSUE THREAD

**Issue by JiaDYuan** [The-OpenROAD-Project/OpenROAD-flow-scripts#1005]
### Description

How to set the synthesis parameter "SYNTH_ARGS"? Seems like there is only one opetion in Makefile: -flatten. So is there any other value? I didn't find any explanation of this varieble.

**Comment by maliberty** [comment]
See the synth command in the yosys manual, we just do:
```
synth  -top $::env(DESIGN_NAME) {*}$::env(SYNTH_ARGS)
```

**Comment by JiaDYuan** [comment]
@maliberty  Thanks, reading YOSYS manual now. I am closing this question.
