### ISSUE TITLE
Long running times for some stages in megaboom

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#1134]
### Description

@louiic FYI

megaboom https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1126 has long running times.

Can some of these stages be sped up?

```
make DESIGN_CONFIG=designs/asap7/megaboom/config.mk elapsed
```

```
Log                       Elapsed seconds
1_1_yosys                       5394
2_1_floorplan                   1850
2_2_floorplan_io                  12
2_3_tdms_place                  4428
2_4_mplace                       210
2_5_tapcell                       11
2_6_pdn                          335
3_1_place_gp_skip_io            2563
3_2_place_iop                     14
3_3_place_gp                   66276
3_4_resizer                     5788
3_5_opendp                      5049
4_1_cts                        57232
4_2_cts_fillcell                  61
No elapsed time found in logs/asap7/megaboom/base/5_1_fastroute.log
```

global routing doesn't complete after 22 hours.

### Suggested Solution

I don't think the synthesis of 2 hours isn't too bad.

However for a 590um^2 design, the following running times strike me as surprising given the speed at which I've seen 4mm^2 designs run: 2_1_floorplan, 2_3_tdms_place, 3_4_resizer, 4_1_cts.

Of the above, 4_1_cts seems like the first thing to have a look at, from the surprising amount of time that it takes.

**Comment by oharboe** [comment]
I don't think the synthesis of 2 hours isn't too bad.

However for a 590um^2 design, the following running times strike me as surprising given the speed at which I've seen 4mm^2 designs run: 2_1_floorplan, 2_3_tdms_place, 3_4_resizer, 4_1_cts.

**Comment by louiic** [comment]
I think if we pre place SRAM, it will go faster.

**Comment by maliberty** [comment]
> I think if we pre place SRAM, it will go faster.

Macro placement isn't taking that long.  Do you mean replace registers with an SRAM?

**Comment by louiic** [comment]
Matt,

Yes … I do mean macro = SRAM.

They are in the netlist now.

Louii

**Comment by tspyrou** [comment]
@louiic The sram work to reduce the netlist size is the highest priority that @oharboe has for you right now.
If the flow can't complete within 6 to 12 hours they will probably abandon using this as a comparison baseline.
At the moment its 4 to 5 days.

**Comment by oharboe** [comment]
Covered by a few specific tasks(create fakeram for register file) for megaboom in https://github.com/Pinata-Consulting/pii-ascenium/issues/11

If that isn't enough, then we have to reconsider.
