### ISSUE TITLE
Support clock in mock-array routing by abutment 

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#1176]
### Description

Using #1174, create a  `flow/settings.mk` file:

```
export DESIGN_CONFIG=designs/asap7/mock-array/config.mk
# Routing by abutment parameters
export MOCK_ARRAY_TABLE         = 8 8 4 4 4 4
export MACRO_BLOCKAGE_HALO      = 0
```

Run `make` and the result should be macros routed by abutment.

Log output:

```
[deleted]
[INFO DRT-0195] Start 15th optimization iteration.
    Completing 10% with 56 violations.
    elapsed time = 00:00:00, memory = 1484.50 (MB).
    Completing 20% with 56 violations.
    elapsed time = 00:00:01, memory = 1811.88 (MB).
    Completing 30% with 56 violations.
    elapsed time = 00:00:01, memory = 1485.00 (MB).
    Completing 40% with 56 violations.
    elapsed time = 00:00:01, memory = 1487.32 (MB).
    Completing 50% with 56 violations.
    elapsed time = 00:00:03, memory = 1810.07 (MB).
    Completing 60% with 56 violations.
    elapsed time = 00:00:03, memory = 1484.50 (MB).
    Completing 70% with 56 violations.
    elapsed time = 00:00:04, memory = 1842.55 (MB).
    Completing 80% with 56 violations.
    elapsed time = 00:00:05, memory = 1484.50 (MB).
    Completing 90% with 56 violations.
    elapsed time = 00:00:06, memory = 1778.36 (MB).
    Completing 100% with 56 violations.
    elapsed time = 00:00:06, memory = 1484.50 (MB).
[INFO DRT-0199]   Number of violations = 56.
[deleted]
[INFO DRT-0180] Post processing.
Elapsed time: 2:24.38[h:]min:sec. CPU time: user 1394.04 sys 28.60 (985%). Peak memory: 1891528KB.
cp results/asap7/mock-array/base/5_2_route.odb results/asap7/mock-array/base/5_route.odb
cp results/asap7/mock-array/base/5_route.odb results/asap7/mock-array/base/6_1_fill.odb
cp results/asap7/mock-array/base/4_cts.sdc results/asap7/mock-array/base/5_route.sdc
cp results/asap7/mock-array/base/5_route.sdc results/asap7/mock-array/base/6_1_fill.sdc
(/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.' /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -exit -no_init  ./scripts/final_report.tcl -metrics ./logs/asap7/mock-array/base/6_report.json) 2>&1 | tee ./logs/asap7/mock-array/base/6_report.log
OpenROAD v2.0-8802-g5b1cfd44e 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO] Deleted 0 routing obstructions
[INFO RCX-0431] Defined process_corner X with ext_model_index 0
[INFO RCX-0029] Defined extraction corner X
[INFO RCX-0008] extracting parasitics of MockArray ...
[ERROR ODB-0390] order_wires failed: net ces_0_1_io_lsbOuts_4, shorts to another term at wire point (23760 12444)
Error: final_report.tcl, 60 ODB-0390
Command exited with non-zero status 1
Elapsed time: 0:01.11[h:]min:sec. CPU time: user 1.03 sys 0.05 (97%). Peak memory: 202568KB.
make: *** [Makefile:705: logs/asap7/mock-array/base/6_report.log] Error 1
```

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/7483585e-ff23-4f8f-a4ef-332d89092ac4)

Here I turn off macros:

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/90d39788-caff-43cb-a171-0052f1d81c6d)

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/44a99c34-e13a-42a8-a8a2-2b148a4a4f4f)

The clock is the upper left pin of the Element:

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/c302a8f8-d0ba-4dd4-90c6-b0bca5659435)

### Suggested Solution

Naively, "make clock work".

**Comment by oharboe** [comment]
To load the children:

```
>>> read_def -child results/asap7/mock-array_Element/base/6_final.def

[INFO ODB-0135] Reading DEF file: results/asap7/mock-array_Element/base/6_final.def
[INFO ODB-0128] Design: Element
[INFO ODB-0138]     Created 80 pins.
[INFO ODB-0139]     Created 552 components and 1512 component-terminals.
[INFO ODB-0140]     Created 2 special nets and 1104 connections.
[INFO ODB-0141]     Created 228 nets and 408 connections.
[INFO ODB-0142] Finished DEF file: results/asap7/mock-array_Element/base/6_final.def
```

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/452f83ae-c5cf-40a9-9033-73b4d7ed4cae)

**Comment by oharboe** [comment]
Here we can see the routing by abutment:

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/6dd8f9e4-b018-4f38-91c4-522aa5472806)

**Comment by oharboe** [comment]
@maliberty What is the significance of the very slightly different green colors on the wire?


![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/a58ac20d-6737-4aca-81ce-f08e02592977)

**Comment by maliberty** [comment]
Most likely you have pin shapes overlapping wire segments.  I don't think it has much importance as the gds will be the same.

**Comment by maliberty** [comment]
Is the issue here about clocks (the title) or rcx (the log)?

**Comment by oharboe** [comment]
> Is the issue here about clocks (the title) or rcx (the log)?

I was, naively, hoping that openroad could "make cts work" when routing by abutment...

**Comment by maliberty** [comment]
What do you want the final clock tree to look like?  Once there is no top level routing the tool has nothing to do.  The clock will be defined by the block designer and the top level array.

**Comment by oharboe** [comment]
> What do you want the final clock tree to look like? Once there is no top level routing the tool has nothing to do. The clock will be defined by the block designer and the top level array.

I dont think there is anything that CTS can legally do as it would have to put the CTS inside the macros. I believe the blockages prevent this, even if it can be seen in the OpenROAD GUI that there is enough space inside the macros. 

There would have to be some sort of "scavenging" of space for the CTS inside the macros. I am sure that "solution" comes with its own problems.

Thoughts?

**Comment by maliberty** [comment]
I think it is too large a leap to do scavenging.  I think you are better off shrinking the macro and leaving some top level space to put in the clock tree.

**Comment by oharboe** [comment]
@nerriav Try horizontal routing by abutment only:

restrict clock to left edge and use `settings.mk`

```
export DESIGN_CONFIG=designs/asap7/mock-array/config.mk
# Routing by abutment parameters
export MOCK_ARRAY_TABLE         = 8 8 4 4 4 6
export MACRO_BLOCKAGE_HALO      = 0
```
