### ISSUE TITLE
Current Version of OpenROAD 6_final.log does not have power numbers

### ISSUE THREAD

**Issue by dalyles** [The-OpenROAD-Project/OpenROAD-flow-scripts#1201]
### Description

In some previous versions of OpenROAD flow scripts, the 6_final.log file had power numbers like this example for <code>gcd</code> for <code>nangate45</code>:

<img width="541" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/2e6e191a-0a0d-49c2-a75d-5abe54771082">

The current version of OpenROAD flow scripts shows this instead, skipping the power measurements entirely.
<img width="563" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/0d6d8fdc-e659-4965-b890-a388d83a6c12">

### Suggested Solution

I'm requesting to bring back the power measurements in 6_final.log as this is very critical information for our applications.
Please let me know when this is included again so I can use the current version of OpenROAD flow scripts.

Thank you.

**Comment by maliberty** [comment]
I recall a while ago there was a crash, perhaps it never got turned back on

**Comment by vijayank88** [comment]
@vvbandeira 
Restore these lines is enough right? https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/6ea30ef768e788300d8c2d818bb40dd588659c87

**Comment by dalyles** [comment]
Hi @vvbandeira,

Restoring those lines worked just fine.
I'm able to see the power numbers.

<img width="537" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/6ca23c4b-2e29-4d88-a0e8-0f486bc1a22e">


Thanks!
