### ISSUE TITLE
Unable to run sky130hd gcd

### ISSUE THREAD

**Issue by dalyles** [The-OpenROAD-Project/OpenROAD-flow-scripts#1241]
### Subject

[Documentation] for documentation errors.

### Describe the bug

Hello again,

I'm trying to get started on running the some of the example flows using the <code>sky130</code> technology file.
What ultimately happens when I run make is that ORFS stops at the placement stage. I'll copy/paste
some of the warnings and error messages that showed up on the console since the entire dump is too large to post here.

### Expected Behavior

The expected behavior is a clean run of <code>gcd</code> in the <code>sky130hd</code> technology file.

### Environment

```shell
N/A
```

### To Reproduce

Input: gcd from sky130hd in makefile
Output: Completed run without interrupts through the flow.

### Screenshots

Here are some warnings/errors:
<img width="1425" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/e62a16ff-105b-45fa-b7ea-e0122a54286c">

<img width="1008" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/99dd94b3-9c5f-4c06-8c1d-448a2939d40a">

The screenshot consists of thousands of lines!
<img width="602" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/3f8cf5c2-aaae-44e2-a9e3-5b6aa6517022">

<img width="959" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/ad072449-2859-48de-b944-736bbed8aecc">

<img width="946" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/59fa9005-9be6-407c-ba5e-4ca02254b532">

This is the where the run interrupts and teminates:
<img width="999" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/95712444/11388783-7508-489c-aa75-a964ffcea712">

**Comment by maliberty** [comment]
This design is passing in the CI so there is something wrong in your setup.  Please describe how you are setting up and running.

**Comment by dalyles** [comment]
I'm simply sourcing env.sh, and then I go to the makefile and uncomment the path to <code>gcd</code> for <code>sky130hd</code>. I'm not doing anything particularly different.

**Comment by dalyles** [comment]
I did a tar for my workspace: 
Try this https://drive.google.com/file/d/1dOsR0v7ycP4Y77LHABrXfxjq2zrPAlos/view?usp=sharing

**Comment by rovinski** [comment]
@dalyles your screenshots are from the design `coyote_tc` not `gcd`

**Comment by rovinski** [comment]
Also it's much much more helpful to copy and paste formatted code instead of screenshots.

**Comment by vijayank88** [comment]
> @dalyles your screenshots are from the design `coyote_tc` not `gcd`

@dalyles Seems you mistakenly uncomment the `coyote_tc` instead of `gcd`. To avoid confusion over editing `Makefile`, directly execute with `make DESIGN_CONFIG=./designs/sky130hd/gcd/config.mk` from `flow` directory.

**Comment by maliberty** [comment]
Please try with the correct design.  Reopen if a problem occurs with gcd

**Comment by dalyles** [comment]
Thank you for clarification. It was an oversight on my part. Apologies for that.
I was able to run gcd successfully.

Thanks everybody!
