### ISSUE TITLE
Make Microwatt Run Error at Ubuntu 22.04

### ISSUE THREAD

**Issue by Gayatri11-oa** [The-OpenROAD-Project/OpenROAD-flow-scripts#1306]
### Subject

[Stage]: Global Router.

### Describe the bug

I am trying to run Sky130hd/microwatt - while 'make' , i am getting an error at Global Routing phase. We have created OpenROAD flow using prebuild binary with latest version.
Here i am attaching the error .tar file for your reference.

Please check this file link "https://drive.google.com/file/d/1-ZJm_5wdyTfz0Z9GZWMDHgBykqd5jX0h/view?usp=sharing" for more detail.

### Expected Behavior

This should complete the run and create final result file.

### Environment

```shell
Ubuntu 22.04
```

### To Reproduce

https://drive.google.com/file/d/1-ZJm_5wdyTfz0Z9GZWMDHgBykqd5jX0h/view?usp=sharing

**Comment by vijayank88** [comment]
@osamahammad21 
Can you please check this issue?
With our CI runs `Centos07` successfully, even in my gcp centos7 locally passing all stage successfully for `microwatt`
But for Ubuntu it is throwing error at GRT.
If I adjust `set_global_routing_layer_adjustment $::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER) 0.25` it completes the GRT stage for Ubuntu.
Why OS conflicts at global routing stage?

Yosys version used by user:
`Yosys 0.31+16 (git sha1 b04d0e09e, clang 10.0.0-4ubuntu1 -fPIC -Os)`

CI uses `Yosys 0.13+15 (git sha1 bc027b2ca, gcc 8.3.1 -fPIC -Os)`

**Comment by maliberty** [comment]
@osamahammad21 works on the detailed router not the global router.  Reassigning.

**Comment by eder-matheus** [comment]
@vijayank88 Our latest run in the CI has a different input for the router. I see differences in the global place stage, like utilization, number of nets, instances, etc. Running the attached test case in a Centos07 machine and a MacOS machine ends with routing congestion, so I don't think we have an OS conflict generating the congestion issue.

@Gayatri11-oa I've noticed you're using older versions of the tools. Could you try it with the latest OpenROAD and Yosys? You can build the binaries in their latest versions with `./build_openroad.sh --local --latest --nice`.

**Comment by vijayank88** [comment]
@eder-matheus 
The difference is synthesis netlist from yosys.

The flow got installed with prebuilt package of OpenROAD, yosys, Klayout.

**Comment by vijayank88** [comment]
@eder-matheus 
Find the attached test case which generated with `yosys 0.13` passing the GRT stage. https://slack-files.com/T01699QAZBQ-F05LAUWJB7U-d568f4c6eb 
The user attached test case used `yosys 0.31`, facing GRT issue. 
Can we suggest the user to use `set_global_routing_layer_adjustment $::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER) 0.25` in `fastroute.tcl` with `FASTROUTE_TCL` variable in `config.mk`?

**Comment by Gayatri11-oa** [comment]
if i update to 0.25 is getting crash during "Check_Antennas".

```
check_antennas
--------------------------------------------------------------------------
[WARNING ANT-0011] -report_violating_nets is deprecated.
[INFO GRT-0043] No OR_DEFAULT vias defined.
openroad: ./src/odb/src/db/dbWireCodec.cpp:481: void odb::dbWireEncoder::newPathVirtualWire(int, odb::dbTechLayer*, odb::dbWireType): Assertion `(jct_id >= 0) && (jct_id < _idx)' failed.
Signal 6 received
Stack trace:
 0# 0x000055D6A77789CD in /usr/bin/openroad
 1# 0x00007FA0BCA42520 in /lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6
 3# raise in /lib/x86_64-linux-gnu/libc.so.6
 4# abort in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x00007FA0BCA2871B in /lib/x86_64-linux-gnu/libc.so.6
 6# 0x00007FA0BCA39E96 in /lib/x86_64-linux-gnu/libc.so.6
 7# odb::dbWireEncoder::newPathVirtualWire(int, odb::dbTechLayer*, odb::dbWireType) in /usr/bin/openroad
 8# grt::RepairAntennas::addWireTerms(grt::Net*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >&, int, int, int, odb::dbTechLayer*, int, std::map<grt::RoutePt, std::vector<grt::Pin*, std::allocator<grt::Pin*> >, std::less<grt::RoutePt>, std::allocator<std::pair<grt::RoutePt const, std::vector<grt::Pin*, std::allocator<grt::Pin*> > > > >&, odb::dbWireEncoder&, std::map<int, odb::dbTechVia*, std::less<int>, std::allocator<std::pair<int const, odb::dbTechVia*> > >&) in /usr/bin/openroad
 9# grt::RepairAntennas::makeNetWire(odb::dbNet*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >&, std::map<int, odb::dbTechVia*, std::less<int>, std::allocator<std::pair<int const, odb::dbTechVia*> > >&) in /usr/bin/openroad
10# grt::RepairAntennas::makeNetWires(std::map<odb::dbNet*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >, grt::cmpById, std::allocator<std::pair<odb::dbNet* const, std::vector<grt::GSegment, std::allocator<grt::GSegment> > > > >&, int) in /usr/bin/openroad
11# ant::AntennaChecker::checkAntennas(odb::dbNet*, bool) in /usr/bin/openroad
12# ant::check_antennas(char const*, bool) in /usr/bin/openroad
13# 0x000055D6A8186A04 in /usr/bin/openroad
14# TclNRRunCallbacks in /lib/x86_64-linux-gnu/libtcl8.6.so
15# 0x00007FA0C0E91028 in /lib/x86_64-linux-gnu/libtcl8.6.so
16# Tcl_EvalEx in /lib/x86_64-linux-gnu/libtcl8.6.so
17# Tcl_Eval in /lib/x86_64-linux-gnu/libtcl8.6.so
18# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in /usr/bin/openroad
19# ord::tclAppInit(Tcl_Interp*) in /usr/bin/openroad
20# Tcl_MainEx in /lib/x86_64-linux-gnu/libtcl8.6.so
21# main in /usr/bin/openroad
22# 0x00007FA0BCA29D90 in /lib/x86_64-linux-gnu/libc.so.6
23# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
24# _start in /usr/bin/openroad
Command terminated by signal 6
Elapsed time: 1:30.40[h:]min:sec. CPU time: user 65.15 sys 0.88 (73%). Peak memory: 1780940KB.
make[1]: *** [Makefile:655: do-5_1_grt] Error 134
make[1]: Leaving directory '/home/gayatri/OpenROAD-flow-scripts/flow'
make: *** [Makefile:655: results/sky130hd/microwatt/base/5_1_grt.odb] Error 2
```

**Comment by vijayank88** [comment]
**NOTE** this crash happens only with Ubuntu20.04/22.04. 
If I run `make global_route_issue` and run the test case with standalone OpenROAD, global routing completes without any error.

**Comment by vijayank88** [comment]
> so I don't think we have an OS conflict generating the congestion issue.

Sorry about this. It was due to yosys changes.

**Comment by eder-matheus** [comment]
> if i update to 0.25 is getting crash during "Check_Antennas".
> 
> ```
> check_antennas
> --------------------------------------------------------------------------
> [WARNING ANT-0011] -report_violating_nets is deprecated.
> [INFO GRT-0043] No OR_DEFAULT vias defined.
> openroad: ./src/odb/src/db/dbWireCodec.cpp:481: void odb::dbWireEncoder::newPathVirtualWire(int, odb::dbTechLayer*, odb::dbWireType): Assertion `(jct_id >= 0) && (jct_id < _idx)' failed.
> Signal 6 received
> Stack trace:
>  0# 0x000055D6A77789CD in /usr/bin/openroad
>  1# 0x00007FA0BCA42520 in /lib/x86_64-linux-gnu/libc.so.6
>  2# pthread_kill in /lib/x86_64-linux-gnu/libc.so.6
>  3# raise in /lib/x86_64-linux-gnu/libc.so.6
>  4# abort in /lib/x86_64-linux-gnu/libc.so.6
>  5# 0x00007FA0BCA2871B in /lib/x86_64-linux-gnu/libc.so.6
>  6# 0x00007FA0BCA39E96 in /lib/x86_64-linux-gnu/libc.so.6
>  7# odb::dbWireEncoder::newPathVirtualWire(int, odb::dbTechLayer*, odb::dbWireType) in /usr/bin/openroad
>  8# grt::RepairAntennas::addWireTerms(grt::Net*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >&, int, int, int, odb::dbTechLayer*, int, std::map<grt::RoutePt, std::vector<grt::Pin*, std::allocator<grt::Pin*> >, std::less<grt::RoutePt>, std::allocator<std::pair<grt::RoutePt const, std::vector<grt::Pin*, std::allocator<grt::Pin*> > > > >&, odb::dbWireEncoder&, std::map<int, odb::dbTechVia*, std::less<int>, std::allocator<std::pair<int const, odb::dbTechVia*> > >&) in /usr/bin/openroad
>  9# grt::RepairAntennas::makeNetWire(odb::dbNet*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >&, std::map<int, odb::dbTechVia*, std::less<int>, std::allocator<std::pair<int const, odb::dbTechVia*> > >&) in /usr/bin/openroad
> 10# grt::RepairAntennas::makeNetWires(std::map<odb::dbNet*, std::vector<grt::GSegment, std::allocator<grt::GSegment> >, grt::cmpById, std::allocator<std::pair<odb::dbNet* const, std::vector<grt::GSegment, std::allocator<grt::GSegment> > > > >&, int) in /usr/bin/openroad
> 11# ant::AntennaChecker::checkAntennas(odb::dbNet*, bool) in /usr/bin/openroad
> 12# ant::check_antennas(char const*, bool) in /usr/bin/openroad
> 13# 0x000055D6A8186A04 in /usr/bin/openroad
> 14# TclNRRunCallbacks in /lib/x86_64-linux-gnu/libtcl8.6.so
> 15# 0x00007FA0C0E91028 in /lib/x86_64-linux-gnu/libtcl8.6.so
> 16# Tcl_EvalEx in /lib/x86_64-linux-gnu/libtcl8.6.so
> 17# Tcl_Eval in /lib/x86_64-linux-gnu/libtcl8.6.so
> 18# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in /usr/bin/openroad
> 19# ord::tclAppInit(Tcl_Interp*) in /usr/bin/openroad
> 20# Tcl_MainEx in /lib/x86_64-linux-gnu/libtcl8.6.so
> 21# main in /usr/bin/openroad
> 22# 0x00007FA0BCA29D90 in /lib/x86_64-linux-gnu/libc.so.6
> 23# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
> 24# _start in /usr/bin/openroad
> Command terminated by signal 6
> Elapsed time: 1:30.40[h:]min:sec. CPU time: user 65.15 sys 0.88 (73%). Peak memory: 1780940KB.
> make[1]: *** [Makefile:655: do-5_1_grt] Error 134
> make[1]: Leaving directory '/home/gayatri/OpenROAD-flow-scripts/flow'
> make: *** [Makefile:655: results/sky130hd/microwatt/base/5_1_grt.odb] Error 2
> ```

Could you attach the files to reproduce the crash? Also, did you run with an older version of OpenROAD? Recently, we have made some fixes in the `repair_antennas` regarding crashes similar to this one.

**Comment by vijayank88** [comment]
@eder-matheus crash related openroad.deb package... Check the above linked issue reported by another user.

**Comment by Gayatri11-oa** [comment]
Thanks Team.
With 8/8 Release - I am able to Make Microwatt Run at Ubuntu 22.04

**Comment by Gayatri11-oa** [comment]
Thanks Team
