### ISSUE TITLE
Command terminated by signal 6

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1365]
### Description

After we replaced the process library, we used the original data and scripts. Modify the script according to the process library, and the signal  6 problem occurs when running to ruote. I also want to ask where to set the fanout transition capacitance of sdc.

### Additional Context

<img width="954" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/dd364a98-fe30-47a6-adcf-66186f9bb6d5">
[logs.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/12357890/logs.tar.gz)
[results_part1.tzr.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/12357891/results_part1.tzr.gz
[results_part2.tzr.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/12357892/results_part2.tzr.gz)
)

**Comment by vijayank88** [comment]
Please attach valid reproducible test case.
Also missing environment setup. goto `tools/OpenROAD` and run `./etc/Env.sh`, copy & paste resulting logs

**Comment by chros098** [comment]
Ok, packaged and uploaded
![131692243081_ pic](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/9c767cf0-2b17-499b-a895-583cdd213a78)
[global_place_gcd_nangate45_base_2023-08-16_17-09 (2)(2).zip](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/12365281/global_place_gcd_nangate45_base_2023-08-16_17-09.2.2.zip)

**Comment by chros098** [comment]
Can it be analyzed from the log that the problem is caused by poor timing

**Comment by vijayank88** [comment]
@chros098 
Unable to run your test case as it's missing the files
```
./run-me-gcd-nangate45-base.sh 
vars-gcd-nangate45-base.sh: line 4: export: `===': not a valid identifier
vars-gcd-nangate45-base.sh: line 5: export: `?=': not a valid identifier
OpenROAD 6a66a6b07a3231b9400ed35d0f4e71eace5f5f4f 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Error: read_liberty.tcl, 25 cannot read file ./platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib.
openroad> 
```
Is that changed anything locally in `./platforms/nangate45/lib and ./platforms/nangate45/lef` ?

**Comment by vijayank88** [comment]
The test case you provided not relevant to the `title` and logs.
Provide steps by step instruction what you've changed and when the crash happened?
Because `nangate45/gcd` is part of CI and able to run successfully.

**Comment by chros098** [comment]
yes, I replaced lib, lef, gds and cdl, because I want to use other processes to run flow,
Maybe there is a problem with the file I compressed. I re-uploaded it. Please take a look again
Put it on the cloud disk：
https://drive.google.com/file/d/1blVHIdQNlMkI0LiVkNl2dCvPoFM_d517/view?usp=drive_link

**Comment by vijayank88** [comment]
> yes, I replaced lib, lef, gds and cdl, because I want to use other processes to run flow, Maybe there is a problem with the file I compressed. I re-uploaded it. Please take a look again Put it on the cloud disk： https://drive.google.com/file/d/1blVHIdQNlMkI0LiVkNl2dCvPoFM_d517/view?usp=drive_link

Please enable public access.

**Comment by chros098** [comment]
sry。done

**Comment by chros098** [comment]
https://drive.google.com/file/d/1blVHIdQNlMkI0LiVkNl2dCvPoFM_d517/view?usp=sharing

**Comment by vijayank88** [comment]
@osamahammad21 
Can you please check about test case that fails during detail routing stage?

**Comment by osamahammad21** [comment]
@chros098 
I am getting this error
[ERROR DRT-0234] via8 does not have single-cut via.
could you please recheck the attached testcase?

**Comment by chros098** [comment]
@osamahammad21 
I repackage the test case 
link ：
https://drive.google.com/file/d/1kSC-TpLAFtIfX8hf9aJopLeK079eOpYl/view?usp=sharing

**Comment by vijayank88** [comment]
@chros098 
Before fixing the issue, can you share information on what you're trying to achieve with the changes you made with nangate45 PDK?

**Comment by osamahammad21** [comment]
@chros098 I found the part of the code that leads to this segmentation fault. I am discussing it currently with Matt to settle on a solution for this.
The main problem is the ill-formed layer via8 that does not have any vias defined in the tech lef. Could you clarify to me why you need such layer?

**Comment by chros098** [comment]
@vijayank88 We mainly want to use our own process library to run flow, but we are not professional in digital aspects, which will cause many basic problems 。The script is based on nangate45, and the environment is also based on nangate45。

**Comment by chros098** [comment]
@osamahammad21 I will check the script of the whole process again, because this script is based on nangate45 and modified from nangate45's script

**Comment by osamahammad21** [comment]
@chros098 We've settled to log an error whenever there is a cut layer that doesn't have any via defined. So from our part we will create a PR with the error added. For you to fix this test case, you need to fix that layer by either adding the required vias or removing the layer at all.

**Comment by chros098** [comment]
@osamahammad21 thanks. I'll try again after modifying。

**Comment by chros098** [comment]
@osamahammad21 @vijayank88
Hello, I have modified the problem of via8, and then continued to run, the problem of signal11 appeared。
The picture below is the error reported
<img width="981" alt="a6a9ac664aefe550ff9846f0f580f45" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/cc46f09f-d95e-47c7-ab8a-9be166248634">
The data used is packed,put on the cloud disk
https://drive.google.com/file/d/1jefhCSjbj71KR638bsYYdVyGsE_CPalv/view?usp=drive_link
Please help me to look again

**Comment by vijayank88** [comment]
@chros098 Enable public access to the above link

**Comment by chros098** [comment]
@vijayank88 https://drive.google.com/file/d/1jefhCSjbj71KR638bsYYdVyGsE_CPalv/view?usp=drive_link 
update thanks

**Comment by vijayank88** [comment]
@chros098 
The attached test case is related to `global_place` stage. Seems you attached wrong test case, the logs shows still an detail routing crash.
Can you re-attach the right test case as per above screen shot, it crash during finish stage?

**Comment by maliberty** [comment]
Did you update the rcx tech file to match whatever other modifications you made?

**Comment by chros098** [comment]
hello ，I have two questions：
1.After modifying the tech file, we ran through the entire flow and finally generated the gds file. Regardless of using klayout and calibredrv to open the gds file, the filter cell does not display the layer, but this cell is called, and the gds file run by nangate45 also has this problem。
2.The whole process runs smoothly. We modified the grid strategy-M1-M4-M7.tcl file in the pdn stage, so that M1 is not used as the power grid layer, so that it can run smoothly. If you do not modify this file, the following problem will be reported.
<img width="960" alt="15c5506a6031f6d39d00ba9512d2b6b" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/781c86f1-0663-4322-946c-d96df901d607">
https://drive.google.com/file/d/13Uk1S_odI0u3XN9ieb-_JKBLOf4btMIF/view?usp=drive_link

**Comment by vijayank88** [comment]
@chros098 
Please attach a valid test case whenever you're reporting some issues.
In the above screenshot shows pdn issue, but given test case running `global_place` stage.

**Comment by chros098** [comment]
thanks 。
I am asking two questions, one is that the filter cell is empty after gds is generated, without any layers. The second problem is that during the pdn process, when the m1 is used as the power network level, an error will be reported.
The link below is the test case for the second problem
https://drive.google.com/file/d/1d5b6o8sSdT6GQHtJbS2-n2GR6IvD-e7Q/view?usp=drive_link
Thanks again

**Comment by osamahammad21** [comment]
PDN is out of my scope. @maliberty could you please check who should be responsible for this?

**Comment by maliberty** [comment]
Please use make issue to produce your test cases rather than making a huge tar with tons of extraneous file.

**Comment by maliberty** [comment]
In nangate45 metal4 is vertical.  In your tech metal4 is horizontal.  It makes no sense to have horizontal metal1 stripes connect to horizontal metal4.  You need to update your pdn grids to use appropriate layers of alternative directions.

**Comment by maliberty** [comment]
The original issue here is resolved.  Please open unrelated issues separately.

**Comment by chros098** [comment]
@maliberty  thanks
