### ISSUE TITLE
Is there a way to download the generated timing report from gui?

### ISSUE THREAD

**Issue by wlgusgit** [The-OpenROAD-Project/OpenROAD-flow-scripts#1394]
### Description

Is there any way to download the timing report on the right section of the gui?
![timing](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/55954610/ee4c6860-cf37-438a-ad03-e575f5dd0f18)

**Comment by maliberty** [comment]
No though you can use the report_checks command to get a text report
