### ISSUE TITLE
The width of the generated gds track and metal becomes 10 times the set

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1405]
### Subject

[Stage]: GDS generation.

### Describe the bug

Using the gds generated by openroad, the track and metal width in the gds become 10 times the set value, and the filter cell is empty.

Test cases are placed on the cloud disk
https://drive.google.com/file/d/1vytqgR7SvbHEZ3GHWbgww63wENlhfN5f/view?usp=drive_link

### Expected Behavior

I hope to find out whether it is a setting problem or a problem with our operation。

### Environment

```shell
using an older version
```

### To Reproduce

Test cases are placed on the cloud disk
https://drive.google.com/file/d/1vytqgR7SvbHEZ3GHWbgww63wENlhfN5f/view?usp=drive_link

**Comment by vijayank88** [comment]
Based on updated LEF file, have you updated KLayout technology file for GDSII generation `FreePDK45.lyt`?

**Comment by chros098** [comment]
This file is not generated, how is this file generated？

**Comment by vijayank88** [comment]
check this: https://openroad-flow-scripts.readthedocs.io/en/latest/contrib/PlatformBringUp.html#klayout

**Comment by chros098** [comment]
thanks. After generating the lyt file according to the tutorial, I ran the process again. There are metal layers in the cell, etc. However, when importing gds, I found an error message and there was no via cell. This cell seemed to be automatically generated. May I ask where this needs to be set?
<img width="879" alt="fbcf66e1555146d83706eeecafcbc4e" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/9772adb6-d388-4536-b401-3eb5f9056950">

https://drive.google.com/file/d/1p-gcb9Hb4s9BpW6qx3U_TKyQp5VJZ_Q4/view?usp=drive_link

**Comment by vijayank88** [comment]
Attach a layer map file to run klayout for gds generation @chros098

**Comment by chros098** [comment]
hlleo here？
<img width="569" alt="d39f1fbc6fe15f57b71a9a66ef0887e" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/468bd1bf-e55d-400e-8a6c-d449a63fb840">

**Comment by vijayank88** [comment]
I've requested you to attach `*.lyp` file.

**Comment by chros098** [comment]
Are you attaching here?
<img width="562" alt="45dc20e72a2405f703a0087fdcff136" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/309bef5f-f036-489f-80f6-e7cb29092794">
lyt and lyp files can be helpful here.
https://drive.google.com/file/d/1kUGkuNiqKuGNnlPttsNefqRd97QrZsG2/view?usp=drive_link

**Comment by vijayank88** [comment]
If I'm right you're derived pdk from FreePDK45(nangate45). So try to use same `.lyt` and `.lyp` from [here]( https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/nangate45/FreePDK45.lyt) if layer names not changed mean and run the flow and check able to get GDS file. @chros098

**Comment by maliberty** [comment]
This seems to have trailed off.  Please reopen if still relevant.

**Comment by maliberty** [comment]
This seems to have trailed off.  Please reopen if still relevant.
