### ISSUE TITLE
rcx file

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1454]
### Subject

[Stage]: Other. Please describe below.

### Describe the bug

May I ask how the rcx file is generated when changing to a new process? Is it automatic or manual?

### Expected Behavior

May I ask how the rcx file is generated when changing to a new process? Is it automatic or manual?

### Environment

```shell
mei
```

### To Reproduce

rcx file

### Screenshots

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/b1cd2510-168b-4dba-b17d-02487a33c9b5)

**Comment by vijayank88** [comment]
@chros098 
Have you referred following document?
https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/rcx/doc/calibration.md
https://github.com/The-OpenROAD-Project/OpenROAD/tree/master/src/rcx

**Comment by chros098** [comment]
thanks

**Comment by chros098** [comment]
Is there an instruction manual for lyt and lyp file generation?
Follow this step to generate
https://openroad-flow-scripts.readthedocs.io/en/latest/tutorials/FlowTutorial.html
The generated one is not quite right
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/63c6b762-ea29-45c5-b673-9c96856fdf44)
There was a problem when reading the layermap
.lyt not good
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/4364f2e0-ef78-46ee-a681-a1714a37800d)
drc and lvs file Is there an instruction manual too?

**Comment by vijayank88** [comment]
https://openroad-flow-scripts.readthedocs.io/en/latest/contrib/PlatformBringUp.html#klayout for KLayout .lyt and .lyp generation.
Compare the file with https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/nangate45/FreePDK45.lyt and remove XML header which are not required.
Keep everything as per flow relative path.

**Comment by chros098** [comment]
Hello, during the process of generating the rcx file, spef has been prepared. When executing the script, it gets stuck on this interface.
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/5bd01337-f511-4b43-aa62-13b7d63ec00c)

**Comment by maliberty** [comment]
Does you generate_pattern.spef files have any contents?  It seems like it doesn't from the corners=0.

**Comment by chros098** [comment]
The spef file generation problem has been solved. It is a problem with the starrc setting. It is encrypted and the software does not recognize it.But now there is a new problem. Import the generated rcx file into folw and follow the openroad process. Finally, there is a problem when extracting rcx.
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/ae0118d3-222e-42ce-ac70-e0f138dda8e6)
I don’t quite understand where this problem occurs. I looked at the tcl script and found no relevant settings.
thanks

**Comment by maliberty** [comment]
It looks like RCX finished and you have a problem after that in the flow.  What are PWR_NETS_VOLTAGES & GND_NETS_VOLTAGES set to?

**Comment by chros098** [comment]
It is the default. I have not modified this value yet. I used a new process to run gcd design.
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/a0334f3c-f697-41d1-a431-4522763a33f7)

**Comment by chros098** [comment]
I set PWR_NETS_VOLTAGES to 3.3v, GND_NETS_VOLTAGES is still 0, same problem

**Comment by chros098** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/1359c153-0c44-4fb6-8963-7bd789567148)
I ignored the following variables again, still the same problem

**Comment by chros098** [comment]
Do the above two variables need to be defined according to different designs? I used the gcd design, but I did not find the definition in the designed config.mk. I only found the definition on the relevant platform.

**Comment by maliberty** [comment]
Since you didn't provide any environment info I don't know what commit you are on and what content of line 60 of your final_report.tcl.  Please indicate what that line contains.

**Comment by chros098** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/97220e22-4ae0-425b-b146-d7cbde6923f4)
I haven't modified the tcl script that comes with openroad. Line 60 is a bracket. I don't want to turn off variables because it is not a public process library and the environment cannot be shared. Sorry

**Comment by maliberty** [comment]
Add "puts $::env(PWR_NETS_VOLTAGES)" and let's see what it shows.  I suspect it is set to something.

**Comment by chros098** [comment]
我仔细的检查了我设计下面的config.mk发现有这两项的定义，是因为我之前进行了测试，没有修改回去。我使用默认的config.mk再跑下

**Comment by chros098** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/42e24c8a-0529-4221-8166-3c739257870b)
I ignored this step of code and prevented it from running ir drop to generate gds, but I still don’t know which variable caused the problem.

**Comment by chros098** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/a80d0627-7423-4c93-bd0b-fb1ab2c393f2)
Everything has been modified, but I am faced with a new problem: it did not recognize the resistance of m7, but I have already defined it in setRC.tcl.

**Comment by chros098** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/72e9046b-3782-447c-8fac-8b08f72f0418)

**Comment by maliberty** [comment]
I don't follow - you should that you commented out analyze_power_grid and then you show an error from it.  Is it enabled or not?

**Comment by maliberty** [comment]
no reponse
