### ISSUE TITLE
[yosys] ERROR: Abort in passes/techmap/extract_fa.cc

### ISSUE THREAD

**Issue by bkoppelmann** [The-OpenROAD-Project/OpenROAD-flow-scripts#147]
**Describe the bug**
When running the design 'riscv32i' for sky130hd like this
```
$ make DESIGN_CONFIG=designs/sky130hd/riscv32i/config.mk
```
then yosys fails with the following error message:
```
28.9. Finished OPT passes. (There is nothing left to do.)
29. Executing EXTRACT_FA pass (find and extract full/half adders).
ERROR: Abort in passes/techmap/extract_fa.cc:178.
Command exited with non-zero status 1
```
I used a locally built yosys using:
```
$  ./build_openroad.sh --local
```

**Expected behavior**
yosys should produce a synthesized netlist for riscv32i with the sky130 pdk

**Environment (please complete the following information):**
Please only report issues for supported OSs.
 - OS: Manjaro Linux
 - OpenROAD-flow commit affb7b4

**Comment by maliberty** [comment]
This looks to be a yosys bug and should be reported to https://github.com/YosysHQ/yosys/issues
