### ISSUE TITLE
`make bash` should put something in the prompt

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenROAD-flow-scripts#1497]
### Description

When you type `make bash` you get a bash shell with all the environment setup as the Makefile would execute things. 

However, it is very easy to forget that you are inside this environment as there is no indication. 

There is also no indication that you have successfully entered the environment.

### Suggested Solution

Things like `conda` and `virtualenv` generally put something into the bash prompt to indicate that you are inside the environment.

**Comment by luarss** [comment]
Any thoughts on this solution? 

https://chat.openai.com/share/2bde157b-2196-4aee-83c4-e28bd3b6b54c

**Comment by maliberty** [comment]
Setting PS1 to something reasonable makes sense
