### ISSUE TITLE
Update scripts to use Ethan's new `dont_use` functionality

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/OpenROAD-flow-scripts#1502]
### Description

@QuantamHD landed a change into both Yosys and ABC to better support `dont_use` functionality. OpenROAD-flow-scripts should probably be updated to use that functionality.

 * Yosys change - https://github.com/YosysHQ/yosys/pull/3892
 * ABC change - https://github.com/berkeley-abc/abc/pull/239

The equivalent change in Silicon compiler can be found @ https://github.com/siliconcompiler/siliconcompiler/pull/1998/files

### Additional Context

One downside is that it means OpenROAD-flow-scripts will depend on having a new enough version of Yosys and ABC.

**Comment by rovinski** [comment]
Resolved in #1809
