### ISSUE TITLE
Error when running openroad

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1579]
### Subject

[Documentation] for documentation errors.

### Describe the bug

运行出现error
<img width="959" alt="c17e2022302023aca8947d0d2bf5589" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/1c9f298d-26cc-41b3-b71f-7f3b4cc0b09d">

### Expected Behavior

Error when running openroad 
<img width="959" alt="c17e2022302023aca8947d0d2bf5589" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/b6d0dcd6-9b61-4cd8-910e-54dffd58e39f">

### Environment

```shell
./etc/Env.sh
```

### To Reproduce

<img width="619" alt="0959d94f850f7b2ec783452eb0bbdc2" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/9f90663f-f2aa-434c-82a3-e5c919e5dda9">

**Comment by maliberty** [comment]
No legal way can be determined to access those pins.  Can you provide a test case?

**Comment by rovinski** [comment]
@chros098 also please copy and paste text rather than posting a screenshot. It helps let others search for similar issues. Thanks!

**Comment by chros098** [comment]
This problem has been solved after checking it
