### ISSUE TITLE
High Cell Delay and Detouring 

### ISSUE THREAD

**Issue by faisaladilquadery** [The-OpenROAD-Project/OpenROAD-flow-scripts#1602]
### Subject

[Stage]: Detail Placement.

### Describe the bug

I have implemented an opensource design in OpenRoad with a foreign commercial PDK. I have noticed high cell delay and detouring.
My analysis is as follows :
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/26ff6c1a-b1b5-44d1-9cd2-574f2ce2ab5c)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/571dc177-500e-4e8a-8bcb-67fa03ba923f)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/aaebee8c-fbe4-4fa6-8d62-88a2706c3ba2)

The Above screenshot is from a floorplan database. If we focus on this particular cell "**INR2D0**" for example, we can notice it has very minimal cell delay and slew.

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/1707f9ea-1972-498e-a93b-f2e9d90fcbed)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/466e4d6f-836c-4131-af63-f235743a39fa)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/de5bf5cf-4632-4f8b-bf39-9a81cc549a56)

The Above screenshot is from the placement stage. We can notice that the delay increased by about 0.1ns (100ps) and the input slew also increased for "**INR2D0**"

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/ce0e9a8c-8e8d-4029-b893-cb2b67dad762)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/53f89204-3534-42fe-b114-3c8683ce5b3b)
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/26730261-20e6-4e20-bd0e-9127085970aa)

The above screenshot is from the route stage. We can notice the delay increased to 0.23 ns ( 200ps ) and the input slew also increased for "**INR2D0**"

The timign path in gui looks represents the following:
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/85042010-0ad2-4251-bd48-ac790c35a171)

**We can notice heavy detouring around this particular marked area in yellow. Why is OpenRoad placing cells in such manner that causes detourings in route? or is this issue more related to the route engine than the placement engine ?**

If we look into the detour path further: 

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/140678965/d9bc7f92-739b-43d2-ae23-587283dbf288)

**The timing paths can be seen with high cell delay,which is the reason for high negetive slack.**
**1. Is there any way to reduce these cell delays?**
**2. What could be the reason for these cell delays and detour paths?**

### Expected Behavior

Lower Negetive Slack

### Environment

```shell
e (found version "1.80.0")  
-- boost: 1.80.0
-- Found Python3: /home/nsl/anaconda3/include/python3.9 (found version "3.9.12") found components: Development Development.Module Development.Embed 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- spdlog: 1.8.1
-- Found BISON: /usr/bin/bison (found version "3.8.2") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- STA version: 2.4.0
-- STA git sha: d26f41708ed89d467c033334b0a3895558c003b4
-- System name: Linux
-- Compiler: GNU 11.4.0
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG
-- Install prefix: /usr/local
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- SSTA: 0
-- STA executable: /home/nsl/OST/nsl/OpenROAD-flow-scripts/tools/OpenROAD/src/sta/app/sta
-- GPU is not enabled
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- Found re2: /opt/or-tools/lib/cmake/re2/re2Config.cmake (found version "9.0.0") 
-- Found Clp: /opt/or-tools/lib/cmake/Clp/ClpConfig.cmake (found version "1.17.7") 
-- Found Cbc: /opt/or-tools/lib/cmake/Cbc/CbcConfig.cmake (found version "2.10.7") 
-- Found Eigen3: /usr/local/share/eigen3/cmake/Eigen3Config.cmake (found version "3.4.0") 
-- Found SCIP: /opt/or-tools/lib/cmake/scip/scip-config.cmake (found version "8.0.1") 
-- GUI is enabled
-- Charts widget is enabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0") found components: serialization 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find VTune (missing: VTune_LIBRARIES VTune_INCLUDE_DIRS) 
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found suitable version "1.80.0", minimum required is "1.78")  
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0") found components: serialization system thread 
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0")  
-- TCL readline enabled
-- Tcl Extended disabled
-- Python3 enabled
-- Configuring incomplete, errors occurred!
```

**Comment by maliberty** [comment]
This test case contains confidential information and there is no NDA in place.  We will not look at it and suggest you take down the data.  If you need support on a proprietary PDK please contact info@precisioninno.com to setup NDAs and support.
