### ISSUE TITLE
digital route violation

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1617]
### Subject

[Stage]: Detail Router.

### Describe the bug

When I added a new process (FinFET process) according to the official documents, I ran to 5-2detail roate. The log showed that there were many via space violations, and then the program kept repairing, but the related errors would not be repaired. The lech is attached to the picture. For the lef via part, please help find the reason, thank you

### Expected Behavior

perfect run 

### Environment

```shell
no
```

### To Reproduce

暂无

### Relevant log output

```shell
暂无
```

### Screenshots

<img width="959" alt="e38bd237ed6b8685728366f82734006" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/f28bec73-e381-4476-bb70-3a33f9a6a8fc">
<img width="576" alt="f41bdabed1b7122a941c920e8047a6a" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/69498618-f564-4a91-bbeb-2ead40e9bd93">
<img width="614" alt="fe8df2a73875f8ba5f62ab40342941b" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/172d0e6a-cc45-41ef-b6a7-b996cbaca933">

### Additional Context

暂无

**Comment by maliberty** [comment]
Can you load the markers in the GUI to see if there is some pattern?  
What is your PDN structure on M1/M2 like?  Do you have parallel rails?

**Comment by chros098** [comment]
We installed a new version of opneroad and some new problems appeared. We will solve the new problems first and then reproduce the problem.

**Comment by chros098** [comment]
I reported a new error after updating the PDN. Please help me check it. Thank you.
<img width="959" alt="2989c74408dcba199183f02219e4098" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/9e8dca11-582e-4eca-869f-1e6bbf916b0f">
<img width="955" alt="a07aba55b12cc163efe465c077d227a" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/e118cdee-3124-4601-a47b-da461f7bf6bd">
<img width="959" alt="101dea485c47c0e355822fe85cd9567" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/2055fac4-e781-470e-84b7-e63dde2d1966">

**Comment by maliberty** [comment]
Please provide a test case as the logs are insufficient to say what is wrong.

**Comment by chros098** [comment]
Sorry, PDK cannot be made public. I will think of another way.

**Comment by maliberty** [comment]
Precision Innovations can provide support under NDA
