### ISSUE TITLE
`eqy` not found

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1618]
### Subject

[Stage]: CTS.

### Describe the bug

During the process of running the nangate45 official use case, a problem occurred in the cts stage.

### Expected Behavior

During the process of running the nangate45 official use case, a problem occurred in the cts stage.

### Environment

```shell
The latest version of the official environment
```

### To Reproduce

nagate45 gcd test

### Screenshots

<img width="416" alt="dd8f6879a9b7f658000bc77ff5e0e27" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/b1f5dd5f-3523-472e-95a9-efda39ad7b2d">
<img width="481" alt="04e881f970b0cc3e651f57e0b1890af" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/a46fe806-98af-4343-8c02-a77cda68690f">

**Comment by vijayank88** [comment]
similar to this issue: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1513

**Comment by vvbandeira** [comment]
Could you try again with the latest code? Please also make sure to `source env.sh` before running the flow if you used `sudo ./setup.sh` to install the dependencies.

(also, closing as duplicated)
