### ISSUE TITLE
KALYOUT drc lvs rule file 

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1654]
### Subject

[Flow] for any util, flow Makefile, or flow script issues.

### Describe the bug

I would like to ask, after adding new technology to openroad, can the lvs drc rule required by klayout be automatically generated?

### Expected Behavior

Generate a rule file that can be used by klayout of a new process

### Environment

```shell
Generate a rule file that can be used by klayout of a new process
```

### To Reproduce

Generate a rule file that can be used by klayout of a new process

**Comment by vijayank88** [comment]
Have you referred this: https://openroad-flow-scripts.readthedocs.io/en/latest/contrib/PlatformBringUp.html#klayout ?

**Comment by maliberty** [comment]
> I would like to ask, after adding new technology to openroad, can the lvs drc rule required by klayout be automatically generated?

No there is no automatic mechanism.
