### ISSUE TITLE
Corners outside of chip area in final GDS

### ISSUE THREAD

**Issue by Syndace** [The-OpenROAD-Project/OpenROAD-flow-scripts#1671]
### Subject

[Stage]: GDS generation.

### Describe the bug

When inspecting the final GDS with KLayout, I noticed the padframe corner cells are placed outside of the chip area. In the DEF (via `make gui_final`), everything looks fine. Screenshots below.

### Environment

Using the docker container, always on the newest master commit. I'm also on the newest commit of OpenROAD, since it includes the fix for https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1646.

### To Reproduce

The following is a minimal self-contained example design to reproduce the issue: 
[corner_issue.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/13525398/corner_issue.tar.gz)

Included in the .tar.gz, in the `results` folder, are the full log, the final GDS and copies of the screenshots I've attached below.

### Screenshots

![gui](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/5029529/e5b3fa81-156f-4fc8-9cec-553c97e0340b)
![klayout](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/5029529/481eb069-b585-4b0f-9b3a-62f97a432ebb)

### Additional Context

I had a very similar issue a year ago, when I used OpenLane and called the "old" padframe commands: https://github.com/The-OpenROAD-Project/OpenROAD/issues/2253
This might be related.

**Comment by maliberty** [comment]
The gds for corner has 0,0 at the lower right instead of the lower left.

**Comment by maliberty** [comment]
I see you have in the LEF
```
MACRO Corner
  CLASS PAD ;
  ORIGIN 180.000 -0.000 ;
```

@gadfort might you look at this as well?

**Comment by maliberty** [comment]
@gadfort ??

**Comment by Syndace** [comment]
This might be a bug in the I/O library, it seems to me that the origin mismatches between LEF and GDS. I have asked the author of the I/O library and will report back once I hear from them.

**Comment by gadfort** [comment]
@maliberty sorry I missed this. Like @Syndace it seems that the GDS has a different origin from the LEF

**Comment by Syndace** [comment]
Okay solved it, it was indeed a bug in the I/O library. Sorry for opening this issue and not checking the I/O library first.

For reference, LEF and GDS don't need to have matching origins; the `FOREIGN` LEF statement is what glues LEF and GDS together. In our case, the `FOREIGN` statement was incorrect for the corner, it specified the GDS origin of the corner as (0,0), when it is (-180,0) in reality.
