### ISSUE TITLE
New DRC errors with latest Yosys on sky130hs/jpeg

### ISSUE THREAD

**Issue by vvbandeira** [The-OpenROAD-Project/OpenROAD-flow-scripts#1698]
### Subject

[Stage]: Detail Router.

### Describe the bug

After updating Yosys to use a newer version, sky130hs/jpeg DRC errors increased from 0 to 1.

### Expected Behavior

DRT should finish with `0` DRC errors same as before Yosys update.

### Environment

```shell
Latest.
```

### To Reproduce

https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-Public/job/public_tests_all/job/master/lastSuccessfulBuild/artifact/flow/final_report_jpeg_sky130hs_base_2023-12-13_13-16.tar.gz

**Comment by vvbandeira** [comment]
@maliberty FYI

**Comment by maliberty** [comment]
Once fixed please reset the metrics limit back to 0
