### ISSUE TITLE
Under the new technology, an error occurs when running the code

### ISSUE THREAD

**Issue by chros098** [The-OpenROAD-Project/OpenROAD-flow-scripts#1724]
### Subject

[Stage]: Synthesis.

### Describe the bug

报错 
<img width="691" alt="3f1effb868ae85f2eddd98b378cddf2" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/f44f0ccd-a309-4e9b-84c1-8390a910e78b">

### Expected Behavior

<img width="691" alt="3f1effb868ae85f2eddd98b378cddf2" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/9c7754d9-95e1-4225-94ad-36d393947a42">

### Environment

```shell
https://drive.google.com/file/d/1mjY2Riwhyp2hQwq8y62tn4a900jJKSKh/view?usp=drive_link 链接在这里
```

### To Reproduce

<img width="691" alt="3f1effb868ae85f2eddd98b378cddf2" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/57aa22cb-8d92-4b6e-a0ce-2d9bc1b24154">

### Relevant log output

```shell
https://drive.google.com/file/d/1mjY2Riwhyp2hQwq8y62tn4a900jJKSKh/view?usp=drive_link
```

### Screenshots

<img width="691" alt="3f1effb868ae85f2eddd98b378cddf2" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/142307210/2c0f7ff8-ee87-4c3d-82ae-d6becaa3e994">

**Comment by vijayank88** [comment]
Is the new technology is opensource? @chros098

**Comment by chros098** [comment]
Not open source

**Comment by vijayank88** [comment]
> Not open source

Remove the drive link and share test case directly with @maliberty with NDA.

**Comment by chros098** [comment]
@maliberty  Hello, how can I share test cases with you?

**Comment by chros098** [comment]
Hello, how can I share test cases with you? @maliberty

**Comment by maliberty** [comment]
We can discuss support and and NDA via [info@precisioninno.com](mailto:info@precisioninno.com)

**Comment by chros098** [comment]
done thanks

**Comment by chros098** [comment]
https://drive.google.com/file/d/1baj54YCxDoi5kA84cavB4zPThX2QSL1c/view?usp=sharing thamks

**Comment by chros098** [comment]
@vijayank88  @maliberty  please

**Comment by maliberty** [comment]
The actual crash is in [abc](https://github.com/berkeley-abc/abc) not openroad.  You might have better luck with an issue there.

I did look at the crash and it is related to an instance of ADH1CSCONV2_12TL40.  This appears to be a full adder cell.  You can provide custom mapping for adders.  For example in ng45:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/0ea230930b57a6fb517521d8c34cb3591815b596/flow/platforms/nangate45/config.mk#L38

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/nangate45/cells_adders.v

Perhaps that will work around the issue.
