### ISSUE TITLE
routing congestion too high error

### ISSUE THREAD

**Issue by lakshmi-sathi** [The-OpenROAD-Project/OpenROAD-flow-scripts#174]
**Describe the bug**
The flow fails for these designs - a serv processor design and a tinyRocket processor design ([tinyRocket & serv_fr](https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs)) with an error 'no ap for w_mask_in[0] terminate called after throwing an instance of 'std::runtime_error' ' during the detailed routing step. 
They are using fakerams generated using [bsg_fakeram generator](https://github.com/bespoke-silicon-group/bsg_fakeram) as placeholders for their memories. 
The logs of the run for these two designs are here: 
https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs/serv_fr/logs
https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs/tinyRocket/logs

**Expected behavior**
Detailed Routing succeeding without 'no ap for ...' error

**Environment **
 - OS: Ubuntu 20.04
 - OpenROAD-flow v2.0-880-gd1c7001ad

**File Uploads**
Just have to place these folders in the 'designs/sky130hd/' directory and run it as usual for reproducing the issue: 
https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs/tinyRocket
https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs/serv_fr

**Additional context**
The congestion issue does not seem to appear on designs without SRAM macros. Different pin widths, pin spacings, and sizes were tried (both large and small) for the SRAM macros but still, the issue persists.

@tspyrou  @taylor-bsg

**Comment by Stephanommg** [comment]
@lakshmi-sathi I ran tinyRocket with master branch of OpenROAD-flow-scripts and master branch of OpenROAD and it didnt get past macro place.

**Comment by lakshmi-sathi** [comment]
@Stephanommg  What was the error faced? 
For me, if you see my logs, it completed Global Route: https://github.com/bsg-idea/bsg_sky130_designs/blob/test_sky130/designs/tinyRocket/logs/5_1_fastroute.log ,
and in detailed routing step it fails. 
Could you get some clue as to what could be causing the flow to fail on it?

**Comment by Stephanommg** [comment]
@lakshmi-sathi first there were some warnings:

[INFO ODB-0226] Finished LEF file:  ./platforms/sky130hd/lef/sky130_fd_sc_hd_merged.lef
[INFO ODB-0222] Reading LEF file: ./designs/sky130hd/tinyRocket/sram_1024x32.lef
[WARNING ODB-0176] error: undefined layer (OVERLAP) referenced
[INFO ODB-0225]     Created 1 library cells
[INFO ODB-0226] Finished LEF file:  ./designs/sky130hd/tinyRocket/sram_1024x32.lef
[INFO ODB-0222] Reading LEF file: ./designs/sky130hd/tinyRocket/sram_64x32.lef
[WARNING ODB-0176] error: undefined layer (OVERLAP) referenced
[INFO ODB-0225]     Created 1 library cells

then, later :

[WARNING PDN-0042] No via added at (12413.761 12108.4 12417.361 12109.601) because the full height of met5 (1.6) is not covered by the overlap.
[WARNING PDN-0042] No via added at (12458.561 12108.4 12462.161 12109.601) because the full height of met5 (1.6) is not covered by the overlap.
[INFO PDN-0034]   - grid CORE_macro_grid_1 for instance frontend.icache.data_arrays_0.data_arrays_0_0_ext.mem
[WARNING PDN-0042] No via added at (218.64 12108.4 222.24 12109.601) because the full height of met5 (1.6) is not covered by the overlap.
[WARNING PDN-0042] No via added at (263.44 12108.4 267.04 12109.601) because the full height of met5 (1.6) is not covered by the overlap.
[INFO PDN-0015] Writing to database.
Command terminated by signal 9
Elapsed time: 10:55.81[h:]min:sec. Average CPU: 43%. Peak memory: 22312256KB.
make: *** [Makefile:431: results/sky130hd/tinyRocket/base/2_6_floorplan_pdn.def] Error 137


I was expecting you to run again with updated master branch on both (OR and ORFS) to make sure we are running the same version.

**Comment by Stephanommg** [comment]
@lakshmi-sathi you can also do 

make detail_route_issue

to pack your synthesis result prior to detailed routing so that I can start detailed routing (for debugging) from the same point of you.

**Comment by lakshmi-sathi** [comment]
@Stephanommg I tried running the tinyRocket with the latest master (of OR and ORFS) like you had suggested and I can confirm that I am getting a similar error like you have mentioned (It's erroring out at PDN)
![image](https://user-images.githubusercontent.com/58559090/136239373-09692adc-7727-4d07-82b2-f11171bb8004.png)

However, with the latest master of OR and 'd1c7001' of ORFS (the default one), the design goes through till routing.

**Note**: I have made a change to the constraint file for both serv and tinyRocket (reduced clock period to 50ns). This change is updated in the [designs repo](https://github.com/bsg-idea/bsg_sky130_designs/tree/test_sky130/designs). After this change, the 'no ap for <pin>' error changes to 'Routing congestion too high' error for both designs (when OR is at 'd1c7001' and ORFS is at latest). 

It is also noted that for the Serv processor design, if the area is increased significantly (above 10000x10000um), then it completes the flow but the resulting GDS is hugely empty, just some small patches of logic seen in the layout (image below)
![image](https://user-images.githubusercontent.com/58559090/136256694-10ce0af4-b4fd-4af5-9cf7-26ac0cfe3613.png)
The small rectangular cut to the right is the fakeram (2x576). If I even slightly reduce the area, the flow fails with 'Routing congestion too high' error during global routing.

This above observation was on OR @ d1c7001 (default) + ORFS latest. Would you recommend using OR latest + ORFS latest alone?  

I tried figuring out how to give 'make detail_route_issue' but couldn't, it doesn't seem to be part of the ORFS make file, could you maybe give me a hint on how to give it, and then maybe I can try and pack the result and upload here for your reference.

**Comment by Stephanommg** [comment]
@maliberty can you help here?

**Comment by maliberty** [comment]
I'll try to see if I can reproduce it.  @lakshmi-sathi it would be a lot simpler if you just ran "make detail_route_issue" in your work area as requested rather than point at git repos.

**Comment by maliberty** [comment]
This comment makes little sense:

latest master of OR and 'd1c7001' of ORFS (the default one), the design goes through till routing.

I guess you meant

latest master of ORFS and 'd1c7001' of OR (the default one), the design goes through till routing.

Please clarify as d1c7001 is an OR commit.

**Comment by Stephanommg** [comment]
@maliberty I think @lakshmi-sathi needs more explanation on how to use "make detail_route_issue".

**Comment by maliberty** [comment]
Just as you would run 'make' in ORFS to run the flow 'make detail_route_issue' will package the test case.  You would run it after the tool has failed and the files are all present.  Any relevant envars should be set as if you were running the tool.

**Comment by lakshmi-sathi** [comment]
@maliberty  Sorry about the confusion, I meant "latest master of ORFS and 'd1c7001' of OR"

Thanks for the pointer!
I have collected the results using 'make detail_route_issue' (on latest master of ORFS and 'd1c7001' of OR'):
[tinyRocket](https://drive.google.com/file/d/1ecu0hiZ9z1J89I1idD6pBEHqi-YKdNWS/view?usp=sharing)
[Serv ](https://drive.google.com/file/d/1iPV30ZZ1wUQF1Evv9CchytA6PvI7s-Os/view?usp=sharing)

An update on what else I have tried:
I tried a core area of 11400x10920um and then tinyRocket is able to complete the flow. However, upon viewing the result most of the space is seen empty, like with Serv, and going for a core area less than the one mentioned, causes the 'Routing congestion too high' issue to pop up during global routiing. 
(The packed result above, is of this latest run)

**Comment by maliberty** [comment]
I downloaded tinyRocket and unpacked it.  In detail_route_tinyRocket_sky130hd_base_2021-10-07_03-00/logs/sky130hd/tinyRocket/base/5_2_TritonRoute.log there is no error and the flow completes.  This doesn't demonstrate the 'no ap ...' error.

**Comment by maliberty** [comment]
I downloaded serv but it shows:

[ERROR GRT-0118] Routing congestion too high.

this reproduces the global route issue not the detail route issue reported here.  Please provide an issue file for the 'no ap' problem.

**Comment by Stephanommg** [comment]
@maliberty I think you missed (at least part of) a [comment ](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/174#issuecomment-936805575) from @lakshmi-sathi. He said that the no ap error is gone, but a "routing congestion too high" appeared. So the error is not the aps anymore. That is part of why I called you.

**Comment by maliberty** [comment]
It would have been better to close this and open a different issue as it was assigned to @Stephanommg for detailed routing and not global routing.  I've retitled it.

serv is a tiny design embedded in a huge amount of empty space (1500 nets but 1.3M instance most of which are fillter/tapcells).  It makes debugging slower to deal with so much useless space.   I'll try to recreate it in a smaller form.

**Comment by maliberty** [comment]
I haven't had luck with making a smaller version and don't want to keep fighting it.  Please produce a version with reasonable utilization (currently 0.02%).  You can use 'make global_route_issue' when you have one.

**Comment by lakshmi-sathi** [comment]
To produce a smaller version I kept a smaller core area of 2280x1680um and ran the flow. Now the utilisation is 5% for serv and it fails at global routing with 'routing congestion too high' error.

Attaching the packed result collected for serv using 'make global_route_issue':
[global_route_serv_frs_sky130hd_base_2021-10-07_22-07.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/7307957/global_route_serv_frs_sky130hd_base_2021-10-07_22-07.tar.gz)


On keeping the same core area of 2280x1680um for the tinyRocket design, it is surprisingly able to complete the flow (however, earlier with much higher core area, it was facing routing congestion). Is that expected?

**Comment by maliberty** [comment]
The problem is that MACRO_PLACE_HALO is too small and there isn't enough space between the standard cells and the ram.  Please try increasing it.  I manually moved the macro 10u east in 4_cts.def and the design routes without trouble.

**Comment by lakshmi-sathi** [comment]
@maliberty Thanks for that pointer!

I tried increasing MACRO_PLACE_HALO but that strangely seemed to result in a worse overflow during the global routing step. I tried increasing MACRO_PLACE_CHANNEL instead and that reduced the overflow and the Serv design completes the flow. 

The max(2*halo, channel) will be the spacing between the macros and between the macros and the boundary am I right? I was trying to understand why increasing the MACRO_PLACE_HALO could have worsened the overflow.
Is it as simple as increasing the halo or increasing the channel to increase the spacing between the macros (and with the boundary) so that there is more room to route the standard cells?

**Comment by taylor-bsg** [comment]
@maliberty any thoughts on Lakshmi's questions?

**Comment by lakshmi-sathi** [comment]
> I tried increasing MACRO_PLACE_HALO but that strangely seemed to result in a worse overflow during the global routing step. I tried increasing MACRO_PLACE_CHANNEL instead and that reduced the overflow and the Serv design completes the flow.

Does this make sense in the context that this issue was happening due to the `set_macro_extension` option?

**Comment by maliberty** [comment]
@eder-matheus any thoughts on the above question?

**Comment by eder-matheus** [comment]
@lakshmi-sathi @maliberty A larger MACRO_PLACE_CHANNEL could result in gcells with more resources near the macro pins, so it makes sense the reduced overflow in this case. I'm not so sure about the MACRO_PLACE_HALO though.

**Comment by lakshmi-sathi** [comment]
@maliberty @eder-matheus Thanks for the reply! It helps.

As the original congestion error is fixed (#220) , I am closing this issue.
