### ISSUE TITLE
[WARNING DRT-0422] No routing tracks pass through the center of Term  clock/io_*

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#1786]
### Subject

[Stage]: Detail Router.

### Describe the bug

This is from ` make DESIGN_CONFIG=designs/asap7/mock-array/Element/config.mk detail_route_issue`

untar  [detail-route.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/14123805/detail-route.tar.gz)

```
$ NUM_CORES=16 ./run-me-mock-array_Element-asap7-base.sh 
OpenROAD v2.0-12049-gb0d81bbb0
[deleted]
[INFO DRT-0150] Reading design.

Design:                   Element
Die area:                 ( 0 0 ) ( 43200 43200 )
Number of track patterns: 32
Number of DEF vias:       0
Number of components:     7823
Number of terminals:      528
Number of snets:          2
Number of nets:           1329

[WARNING DRT-0422] No routing tracks pass through the center of Term clock
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[0]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[10]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[11]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[12]
[WARNING DRT-0422] No routing tracks pass through the center of Term io_ins_down[13]
...
```

### Expected Behavior

No error or warning

### Environment

```shell
OpenROAD v2.0-12049-gb0d81bbb0
```

### To Reproduce

See above

**Comment by maliberty** [comment]
Is this different from the usual mock array which has manual macro placement?

**Comment by oharboe** [comment]
> Is this different from the usual mock array which has manual macro placement?

No, this happens on master. I dont recall seeing it, but it is a long time since I studied mock array.

I saw it on a gigabyte example and thought it was better to report on this tiny testcase.

**Comment by maliberty** [comment]
The warning itself was added some months ago so it may have always been there.  Is your larger test case manually placed or mpl2?  This is more of a macro placement issue that the router is just warning about.

**Comment by oharboe** [comment]
> The warning itself was added some months ago so it may have always been there. Is your larger test case manually placed or mpl2? This is more of a macro placement issue that the router is just warning about.

There is no macro placement involved in this test case. This happens on the Element level, not in the array.

**Comment by maliberty** [comment]
It sounds like a pin placement issue then as the pins should be on track.

**Comment by eder-matheus** [comment]
All the pins are properly placed and aligned with the routing tracks.

Vertical pins:
<img width="1035" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/43450810/193469c5-b432-43ee-956c-fd711e2c11a1">

Horizontal pins:
<img width="485" alt="image" src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/43450810/687254ad-ff51-4daa-bff6-a99027a85427">

I also checked the manufacturing grid, and it's also correct.

**Comment by maliberty** [comment]
Is the warning erroneous then?

**Comment by eder-matheus** [comment]
> Is the warning erroneous then?

That's what it seems. I'm looking at the DRT code to understand why the warnings, but it seems to be a bug.
