### ISSUE TITLE
By enabling Metal density rules flow failed to complete

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#1808]
### Subject

[Stage]: GDS generation.

### Describe the bug

I am working on private PDK.
Trying to use https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/sky130hd/fill.json file format and flow failed to complete GDS generation.

If I update https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/sky130hd/gcd/config.mk file with `export USE_FILL =1` failed to complete gds generation.

### Expected Behavior

Complete GDS generation with metal fill insertion.

### Environment

```shell
latest
```

### To Reproduce

If I update https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/sky130hd/gcd/config.mk file with `export USE_FILL =1` failed to complete gds generation.

make DESIGN_CONFIG=./designs/sky130hd/gcd/config.mk USE_FILL=1

### Relevant log output

```shell
Warning: No mapping for layer 'met2', purpose 'FILL' - layer is ignored
Warning: No mapping for layer 'met3', purpose 'FILL' - layer is ignored
Warning: No mapping for layer 'met4', purpose 'FILL' - layer is ignored
Warning: No mapping for layer 'met5', purpose 'FILL' - layer is ignored
[INFO] Reporting cells prior to loading DEF ...
[INFO] Reading DEF ...
[INFO] Clearing cells...
[INFO] Merging GDS/OAS files...
	/home/vijayan/PII/OpenROAD-flow-scripts/flow/platforms/sky130hd/gds/sky130_fd_sc_hd.gds
[INFO] Copying toplevel cell 'gcd'
INFO: Reading config file: /home/vijayan/PII/OpenROAD-flow-scripts/flow/platforms/sky130hd/fill.json
ERROR: No overload with matching arguments in Cell.shapes
  /home/vijayan/PII/OpenROAD-flow-scripts/flow/util/def2stream.py:92
  /home/vijayan/PII/OpenROAD-flow-scripts/flow/util/def2stream.py:140
Command exited with non-zero status 1
```

**Comment by maliberty** [comment]
Fixed
