### ISSUE TITLE
Flow not able to pass global placement stage

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#183]
**Describe the bug**
I'm trying to run dcache module with latest OR commit but failing at global placement. 3_1_place_gp.log with below message.

[INFO GRT-0017] Processing 335 blockages on layer met4.
[INFO GRT-0017] Processing 334 blockages on layer met5.

[INFO GRT-0053] Routing resources analysis:
          Routing      Original      Derated      Resource
Layer     Direction    Resources     Resources    Reduction (%)
---------------------------------------------------------------
li1        Vertical            0             0          0.00%
met1       Horizontal    8778120       4098612          53.31%
met2       Vertical      6583590       3948168          40.03%
met3       Horizontal    4389060       2636068          39.94%
met4       Vertical      2633436       1318042          49.95%
met5       Horizontal     877812        438904          50.00%
---------------------------------------------------------------

Command terminated by signal 9
Elapsed time: 1:26:30[h:]min:sec. Average CPU: 98%. Peak memory: 14908768KB.

How to Run:
Update below line in Makefile and do make:
DESIGN_CONFIG=./designs/sky130hd/dcache/config.mk

**Expected behavior**
Need to generate GDSII with successful complete

**Environment (please complete the following information):**
Please only report issues for supported OSs.
 - OS: Ubuntu 20.04
 - OpenROAD-flow commit: Latest OR commit v2.0-1256-ga7fe7aa9c
 - 
File Uploads**
Attached src file and other logs
[dcache.zip](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/7310759/dcache.zip)

**Comment by maliberty** [comment]
I ran with the commit specified and your zip file but I get:

[InitialPlace]  Iter: 20 CG Error: 0.00004177 HPWL: 5835393036
[ERROR GPL-0302] Use a higher -density or re-floorplan with a larger core area.
Given target density: 0.66
Suggested target density: 0.88
Error: global_place.tcl, 63 GPL-0302

I can't reproduce the result you state.  The above shows that the density is too high.

**Comment by vijayank88** [comment]
@maliberty  try below DIE and CORE AREA. You'll get my attached logs.
export DIE_AREA    = 0.0 0.0 4568.875 4579.595
export CORE_AREA   = 5.52 10.88 4563.16 4568.64

**Comment by maliberty** [comment]
@vijayank88 with those values it runs through without error.  Please package a proper test case.

**Comment by vijayank88** [comment]
@maliberty Is that able to complete GDSII generation?
May I know your latest OR using and system configuration?

Still I'm facing Command terminated by signal 9. What its point?

**Comment by maliberty** [comment]
Yes it goes all the way through to gds.   
OR: ab532069fb9d60c9e0fa7fa72fa65a311eb55bd9
ORFS: 6e4164b077ca7dbb51673aca2b201f5d53f90ae3

Are you running inside docker?  We have seen cases where hitting the memory limit causes a process to be killed.

**Comment by maliberty** [comment]
![image](https://user-images.githubusercontent.com/761514/137037607-a45b369e-5dd7-46ab-aab7-5dfffdb9cfc6.png)

**Comment by dralabeing** [comment]
@vijayank88 Please re-test without docker. Also attach a fully-contained tarball when submitting issues to help reproduce easily and correctly. Thanks

**Comment by vijayank88** [comment]
@dralabeing @maliberty thanks. I tried with latest OR commit. Still flow got terminated by signal 9. I've installed ORFS locally and tried with 16GB RAM and 80GB free space available. Its Single core processor. If its related to memory we can close this issue as you're able to generate GDSII. I will attach my tarball for your reference.

**Comment by rovinski** [comment]
@vijayank88 On my machine it uses a peak of 48 GB for global place.

The main problem is your design is instantiating 8 KB of synthesized RAM. You should be using a memory compiler to generate these RAMs.

The memory and runtime of the flow is related to the number of instances created (as well as the total area). Your design is using over 700k instances, which is, relatively speaking, a very large design. I would not expect to be able to handle any design over ~400k instances on a 16 GB machine.

If you use a memory compiler, it will probably reduce the runtime and memory requirements by a few orders of magnitude. Definitely enough to run on your machine.

**Comment by vijayank88** [comment]
@rovinski thanks for the pointing the memory compiler issue. Can you help how to install/use memory compiler to resolve such issues on OL?

**Comment by rovinski** [comment]
No, not really. I focus on OpenROAD and OpenROAD-flow-scripts. I believe most people are using [OpenRAM](https://github.com/VLSIDA/OpenRAM) for Sky130/OpenLane. You should ask in the Sky130 Slack or the OpenLane repo.
