### ISSUE TITLE
CTS stuck or froze

### ISSUE THREAD

**Issue by velmuruganvmtor** [The-OpenROAD-Project/OpenROAD-flow-scripts#1883]
https://drive.google.com/file/d/1lTD0LWHQKe4YIGO5gcVMMWbYTnUfmqW2/view?usp=sharing
i have uploaded cts issue 
any suggestions please ask
give me any answers to solve this problem

**Comment by rovinski** [comment]
Please use the official issue template and describe your issue in more detail.
