### ISSUE TITLE
LSOracle compilation terminated for readline/history.h

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#198]
I'm using Ubuntu 20.04. Not able to build docker based openroad flow.

git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
cd OpenROAD-flow-scripts
./build_openroad.sh

Note: ./build_openroad.sh --local working fine.

**Describe the bug**
* [Build] for compilation-related issues
Scanning dependencies of target lsoracle
[ 91%] Building CXX object core/CMakeFiles/lsoracle.dir/kahypar_config.cpp.o
[ 94%] Building CXX object core/CMakeFiles/lsoracle.dir/lsoracle.cpp.o
[ 97%] Building CXX object core/CMakeFiles/lsoracle.dir/kahypar_temp_config.cpp.o
In file included from /LSOracle/lib/alice/include/alice/cli.hpp:46,
                 from /LSOracle/lib/alice/include/alice/api.hpp:42,
                 from /LSOracle/lib/alice/include/alice/alice.hpp:36,
                 from /LSOracle/core/lsoracle.cpp:6:
/LSOracle/lib/alice/include/alice/readline.hpp:47:10: fatal error: readline/history.h: No such file or directory
 #include <readline/history.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Expected behavior**
Successful Docker based installation .

**Environment (please complete the following information):**
Please only report issues for supported OSs.
 - OS: Ubuntu 20.04
 - OpenROAD-flow commit: latest commit

**Comment by dralabeing** [comment]
@vvbandeira I had the same problem with the docker installation as reported as above - sent separately via email. readline dependency issue in the docker seems to be the problem

**Comment by vvbandeira** [comment]
Could you try:
```
docker system prune
docker pull openroad/centos7-dev:latest
docker run --rm openroad/centos7-dev:latest ls /usr/include/readline
```

**Comment by vijayank88** [comment]
@vvbandeira give command  to follow for ubuntu as well.

**Comment by vvbandeira** [comment]
@vijayank88 these are docker commands, they should work on any OS with docker installed

**Comment by vijayank88** [comment]
docker system prune
docker pull openroad/centos7-dev:latest
docker run --rm openroad/centos7-dev:latest ls /usr/include/readline


After run this commands, able to do docker based installation. Thanks @vvbandeira

**Comment by dralabeing** [comment]
@vvbandeira - Please add these commands to the documentation for docker based installation
