### ISSUE TITLE
make synth should fail on syntax error in .lib file

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#2055]
### Subject

[Stage]: Synthesis.

### Describe the bug

I don't think I can create a `make issue` for a synthesis problem...

1. untar [synth-lib-no-error.tar.gz](https://github.com/user-attachments/files/15774609/synth-lib-no-error.tar.gz)
2. `git apply patch.txt`
3.  `make DESIGN_CONFIG=designs/asap7/mock-array/config.mk nuke synth`

This should have produced an error, because Element.lib contains a syntax error.

Also, we can see that the `module Element` has not been black-boxed:

```
$ grep Element results/asap7/mock-array/base/1_synth.v |grep mod
module Element(clock, io_ins_down, io_ins_right, io_ins_up, io_ins_left, io_outs_down, io_outs_right, io_outs_up, io_outs_left, io_lsbIns_1, io_lsbIns_2, io_lsbIns_3, io_lsbIns_4, io_lsbIns_5, io_lsbIns_6, io_lsbIns_7, io_lsbOuts_0, io_lsbOuts_1, io_lsbOuts_2, io_lsbOuts_3, io_lsbOuts_4
```

### Expected Behavior

Error when synthesis fails

### Environment

```shell
w$ git log -1
commit a07896053646089750ccebda897c553b385b6bcb (HEAD, origin/master, origin/HEAD)
Merge: c1a0f94a 673fda21
Author: Matt Liberty <mliberty@precisioninno.com>
Date:   Sun Jun 9 13:11:59 2024 +0200

    Merge pull request #2050 from The-OpenROAD-Project-staging/secure-yosys0.42
    
    update Yosys submodule to version 0.42
```

### To Reproduce

See above

**Comment by maliberty** [comment]
This would be an issue for yosys not OR/ORFS.
