### ISSUE TITLE
Yosys does not comile on Ubuntu 21.10

### ISSUE THREAD

**Issue by simonwaid** [The-OpenROAD-Project/OpenROAD-flow-scripts#206]
Running ./build_openroad.sh --local fails on Ubuntu 21.10. The reason is that the version of yosys used by open road is outdated and does not compile. 

Newer version of yosys (e.g. 0.10) compile on Ubuntu 21.10. Version 0.8 and older don't

Also, new features such as support for struct have been added to yosys, so upgrading would also make sense from that perspective.

A workaround:
- Call ./build_openroad.sh --local, and wait until it fails
- Checkout the newest version yosys in the tools directory. 
- In build_openroad.sh change ABCREV to default 
- Run ./build_openroad.sh -l --no_init --local

**Comment by maliberty** [comment]
@rovinski do you have time to look into a yosys upgrade?

**Comment by rovinski** [comment]
@maliberty that depends, is this a scenario where I should update Yosys regardless of the impact on QoR, or can I update it only if it improves QoR? The last time we tried this, the update got rejected because it worsened QoR.

**Comment by maliberty** [comment]
@rovinski I don't recall what happened last time but we can't avoid updating forever.  Would you try it and let's see what the results are.   If the degradation is minor we can go ahead.   If it is major then Andy can probably help; otherwise we can file issues with yosyshq.

**Comment by rovinski** [comment]
@maliberty Ok I'll do that in the background over the next few days.

**Comment by maliberty** [comment]
@rovinski any update?

**Comment by simonwaid** [comment]
@rovinski Any update?

**Comment by rovinski** [comment]
Yosys was updated in #325. If it doesn't compile then it's not related to the version.

**Comment by vvbandeira** [comment]
> Yosys was updated in #325. If it doesn't compile then it's not related to the version.

Closing based on the last comment, please reopen if it is still relevant.
