### ISSUE TITLE
asap7/mock-array: Re-enable simulate and power

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/OpenROAD-flow-scripts#2264]
### Description

Debug and implement fixes required to reenable simulate and power steps for mockarray that were disabled in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/f2f37027d1369c52a7c4d35cf251769f071abd87.

### Suggested Solution

Review CI failure and determine next steps

**Comment by oharboe** [comment]
Added some post-merge review comments to be addressed.
