### ISSUE TITLE
make issue issues

### ISSUE THREAD

**Issue by jjcherry56** [The-OpenROAD-Project/OpenROAD-flow-scripts#230]
The make issue target fails to include setRC.tcl

source $::env(PLATFORM_DIR)/setRC.tcl
[ERROR STA-0511] cannot open './platforms/asap7/setRC.tcl'.
Error: cts.tcl, 30 STA-0511

The TIME_CMD variable value is not portable and generates a syntax error
Error: vars-jpeg-asap7-base.tcl, 6 invalid command name "h:"

set env(TIME_CMD) "/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.'"

**Comment by vijayank88** [comment]
@jjcherry56 
set below variable in design config.mk
export SET_RC_TCL              = $(PLATFORM_DIR)/setRC.tcl

Else override this variable in platforms/asap7/config.mk have incorrect path.

**Comment by rovinski** [comment]
@vijayank88 that's not the problem. This is completely separate. `make *_issue` is supposed to package a complete test case and it is missing files required to make the testcase run.

**Comment by vvbandeira** [comment]
@jjcherry56 can you check the tar files generated by the #249 to see if it fixes the issue?
You can find them here: https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-script-Public%2Fpublic_tests_all-pr/detail/PR-249-head/1/artifacts
