### ISSUE TITLE
Standardize on default CORNER variable definition for platforms

### ISSUE THREAD

**Issue by dralabeing** [The-OpenROAD-Project/OpenROAD-flow-scripts#231]
Currently, there is no specific definition/selection for default CORNER in the platform config.mk. This is random for current PDKS including skywater130, nangate45, asap7 etc.

This should be clarified in the documentation as well.

**Comment by dralabeing** [comment]
@maliberty Please re-assign to the appropriate team member if needed

**Comment by maliberty** [comment]
@tspyrou @louiic @abk-openroad @rovinski  please comment on what you think the default corner should be.

We are currently inconsistent on our default corner, e.g.:
gf12: BC
tsmc65lp: WC

**Comment by rovinski** [comment]
The reasoning for gf12 BC was that BC + margin = best chance of getting functional chips due to being extra cautious about hold slack.

Is multi-corner optimization in OR yet? Is it possible that the answer should be "both" and we add multi-corner support?

**Comment by maliberty** [comment]
@rovinski if we had multi-corner I wouldn't have to ask....

**Comment by rovinski** [comment]
Just checking ¯\\\_(ツ)\_/¯
I would stick with BC.

**Comment by vijayank88** [comment]
@maliberty For ASAP7 we will stick to BC. I'm facing issue with TC for DFF library read.

**Comment by tspyrou** [comment]
The OpenROAD app itself supports multi corner optimization in the flow.
Unit tests like https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/test/gcd_sky130hd_fast_slow.tcl test it.
This feature needs to be propagated up to the flow scripts. The default can then be BC and WC with users able to add more corners as needed.

**Comment by gadfort** [comment]
This is how we handle corners at the moment in our flow: https://github.com/The-OpenROAD-Project-private/OpenROAD-flow-scripts/tree/flow-corners I can open a PR if this is of interest to incorporate

**Comment by tspyrou** [comment]
@arlpetergadfort please do make a PR and thanks for doing the work of integrating the new feature up to ORFS.

**Comment by gadfort** [comment]
@tspyrou I opened #237

**Comment by vijayank88** [comment]
@dralabeing 
Seems resolved. Can we close this?
