### ISSUE TITLE
howto generate swerv_wrapper.sv2v.v

### ISSUE THREAD

**Issue by janboeye** [The-OpenROAD-Project/OpenROAD-flow-scripts#2391]
### Description

Excuse me, I have a question that may not be appropriate from here, but I'm hoping someone can assist. How does one generate the 'swerv_wrapper.sv2v.v' file? Thank you in advance for any guidance.

**Comment by maliberty** [comment]
I believe https://github.com/zachjs/sv2v is used (there are several versions floating around but I think that's right).
