### ISSUE TITLE
GDS generated with unmapped layers in klayout for sky130hd

### ISSUE THREAD

**Issue by tuohangzeng** [The-OpenROAD-Project/OpenROAD-flow-scripts#298]
**Describe the bug**

* [Flow] The flow script can successfully generate the results (including the gds) with all the routings. But when the gds is imported into klayout, the metal layers (e.g. met2 drawing) become empty with the [lyp](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/platforms/sky130hd/sky130hd.lyp) file loaded. Screenshots for klayout before and after loading the lyp file is shown below.

**Expected behavior**
* Routings are correctly mapped to the different metal drawing layers.

**Screenshots**
* Before loading lyp
![image](https://user-images.githubusercontent.com/24362921/147857575-f63e05fe-563a-45df-ab54-6796ec46a38f.png)

* After loading lyp (with "Add other layer entries" and "Hide empty layers" selected) 
  - Several layers only have the "layer/datatype" name
![image](https://user-images.githubusercontent.com/24362921/147857596-97ccca7b-b891-4e03-b22a-d3f7369121a5.png)

**Environment (please complete the following information):**
 - OS: CentOS Linux 7
 - OpenROAD-flow commit 1a27533

**File Uploads**
[gcd_sky130hd_base_2022-01-01_17-44.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/7798054/gcd_sky130hd_base_2022-01-01_17-44.tar.gz)

**Comment by rovinski** [comment]
The `.lyp` file doesn't change any properties of the GDS; it only changes the way it is rendered in the viewer (layers, colors, labels, etc.). That being said, it definitely looks like some layers aren't being mapped correctly by the `.lyt` file.

**Comment by maliberty** [comment]
@rovinski yes and I can't reproduce the problem @ ucsd.  I am guessing an old version of klayout at Michigan but I don't know.  m2 is being mapped to 7/0 which is wrong and not in the lyt.

**Comment by tuohangzeng** [comment]
Thank you, @rovinski and @maliberty! It was indeed related to the .lyt file. After doing a diff with OpenLane and making a few changes, all layer mappings are correct.

**Comment by msaligane** [comment]
@tuohangzeng Please remember to send a PR to update this .lyt file in orfs as well.

**Comment by maliberty** [comment]
What did you change?  I don't see any errors when I run ORFS with the current file.
