### ISSUE TITLE
make issue tarfile errors

### ISSUE THREAD

**Issue by jjcherry56** [The-OpenROAD-Project/OpenROAD-flow-scripts#365]
untaring this issue file:

https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-Nightly-Public/1283/artifact/flow/final_report_bp_multi_nangate45_base_2022-02-23_22-58.tar.gz

produces 2 errors:
x final_report_bp_multi_nangate45_base_2022-02-23_22-58/./platforms/nangate45/fastroute.tcl: Can't create 'final_report_bp_multi_nangate45_base_2022-02-23_22-58/platforms/nangate45/fastroute.tcl'

x final_report_bp_multi_nangate45_base_2022-02-23_22-58/./platforms/nangate45/tapcell.tcl: Can't create 'final_report_bp_multi_nangate45_base_2022-02-23_22-58/platforms/nangate45/tapcell.tcl'

**Comment by maliberty** [comment]
This must be a mac issue as it untar for me just fine.  I guess the /./ might be the trigger, though many other files seem to have that pattern.
