### ISSUE TITLE
Detailed placement failed on _208263_

### ISSUE THREAD

**Issue by AnikBalo** [The-OpenROAD-Project/OpenROAD-flow-scripts#371]
I was trying to implement a 200000+ instance count design in OpenROAD flow with skywater130hd PDK but every time the flow got terminated in detail routing stage. I have tried with different utilization, aspect ratio and place density, but it failed in detail placement stage.  
![image](https://user-images.githubusercontent.com/96606368/157001634-145a396a-99ad-47ba-b641-f839da126ce6.png)

Here is my .def and config.mk:
[issue.zip](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/8171593/issue.zip)

**Comment by vijayank88** [comment]
![Screenshot from 2022-03-03 12-01-49](https://user-images.githubusercontent.com/85787913/156511090-fb1db257-ee96-427e-b673-aec579dce2ff.png)

Check the placement density. Its too high.
Update the following in config.mk and re-try:
```
export CORE_UTILIZATION = 20 
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 2
#
export PLACE_DENSITY = 0.60
```
Try with different density and make sure no red dots in placement density. If still facing issue share `VERILOG_FILES`.

**Comment by vijayank88** [comment]
@AnikBalo Check the above and update me

**Comment by AnikBalo** [comment]
@vijayank88 Yes. I am trying with different density. Currently, I am trying with export PLACE_DENSITY = 0.50. I got this:
![image](https://user-images.githubusercontent.com/96606368/156582476-8ee5b503-10c0-4823-a72b-f44bd275ca4a.png)
![image](https://user-images.githubusercontent.com/96606368/156582602-de035d0b-9952-4c11-96ca-ea7374e90b4c.png)
Now, I am running this with  PLACE_DENSITY = 0.40. 
I will let you know what happend. 
Thanks a lot.

**Comment by AnikBalo** [comment]
Here I tried with different place density but failed to complete full run.
####Setting Place Density: 0.3
Flow terminal:
 
![image](https://user-images.githubusercontent.com/96606368/156704233-a31a33dd-8b99-41d5-b867-0e282b5ac565.png)



Placement Density:
 
![image](https://user-images.githubusercontent.com/96606368/156704252-b4822edc-8779-4d2f-8f93-4114d697a37a.png)


####Setting Place Density: 0.2
Flow Terminal: 
 
![image](https://user-images.githubusercontent.com/96606368/156704281-416cd241-47c7-4117-ab26-0bd747d982bc.png)




##### New Setting: 
export CORE_UTILIZATION = 20
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 2
#
export PLACE_DENSITY = 0.25

Flow Terminal: 
 
![image](https://user-images.githubusercontent.com/96606368/156704321-62cd4f41-1c25-4c3e-a008-11261dcfcf32.png)



Placement Density:
 
![image](https://user-images.githubusercontent.com/96606368/156704367-d4243464-a0e0-489b-ad22-608abe277035.png)


@vijayank88 Here is my data: 
https://drive.google.com/file/d/1f-v3DRlYhyvd93hU1n7uEpONAmWhVBjw/view?usp=sharing

**Comment by vijayank88** [comment]
@AnikBalo 
I will check and update you.

**Comment by vijayank88** [comment]
@AnikBalo 
What is your system configuration?
System RAM?

**Comment by AnikBalo** [comment]
@vijayank88 I am using it on two place. One is my vmware with 8GB ram and 70 GB storage and in another pc with 8GB ram with 150GB storage.  both have ubuntu 20.04 OS

**Comment by vijayank88** [comment]
@AnikBalo 
Terminated by signal 9 is not have enough system resource to run I think. That's why when its reaches 7.25GB its got terminated. Is possible to increase your system RAM and re-try?
CORE_UTIL=20 will work for your design.

**Comment by AnikBalo** [comment]
@vijayank88 I was also thinking about that. I am trying to increase my resources. If I could manage, then I will let you know what happened. 
Thanks a lot @vijayank88  for guiding.

**Comment by AnikBalo** [comment]
I have just increased my resources. Now Ram = 16 GB, 8 core. Still this happened: 
PLACE_DENSITY = 0.6
![image](https://user-images.githubusercontent.com/96606368/156757505-c5f38964-dc8f-4e4d-8d26-48cc9a09ab0e.png)

The Def:
![image](https://user-images.githubusercontent.com/96606368/156757571-60bdb66b-e73c-4b64-889e-c3cbe2105047.png)


Now I am started implementing with PLACE_DENSITY = 0.5.
I will let you know what happened @vijayank88

**Comment by vijayank88** [comment]
@AnikBalo Check the peak memory when its fail. Again terminated by signal 9 with 15GB RAM. Still its looks more resource?
Let me test in cloud server and update you tomorrow.

**Comment by vijayank88** [comment]
@AnikBalo 
Other way try to do macro hardening and implement the flow. So that it will not require much memory during routing.

**Comment by AnikBalo** [comment]
@vijayank88 ok

**Comment by vijayank88** [comment]
@AnikBalo Follow this instruction for how to create test case, if flow fails at any stage of flow.
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/377

**Comment by vijayank88** [comment]
@AnikBalo With attached test case https://drive.google.com/file/d/1f-v3DRlYhyvd93hU1n7uEpONAmWhVBjw/view?usp=sharing itself able to run routing in my cloud server without any issues.
Few updates you can do is increase your routing core number(You've mentioned 8 cores have currently). Update following in `config.mk`
```
export NUM_CORES='6'
```

See my logs:
Running cloud server with 128GB RAM and 32 CORE machine.
```
[INFO DRT-0181] Start track assignment.
[INFO DRT-0184] Done with 981779 vertical wires in 11 frboxes and 614195 horizontal wires in 11 frboxes.
[INFO DRT-0186] Done with 207731 vertical wires in 11 frboxes and 165527 horizontal wires in 11 frboxes.
[INFO DRT-0182] Complete track assignment.
[INFO DRT-0267] cpu time = 00:05:11, elapsed time = 00:01:13, memory = 7168.23 (MB), peak = 10371.75 (MB)
[INFO DRT-0187] Start routing data preparation.
[INFO DRT-0267] cpu time = 00:00:03, elapsed time = 00:00:03, memory = 7432.49 (MB), peak = 10371.75 (MB)
[INFO DRT-0194] Start detail routing.
[INFO DRT-0195] Start 0th optimization iteration.
    Completing 10% with 0 violations.
    elapsed time = 00:01:44, memory = 24770.47 (MB).
    Completing 20% with 38990 violations.
    elapsed time = 00:03:54, memory = 39857.80 (MB).
    Completing 30% with 49080 violations.
    elapsed time = 00:04:26, memory = 39859.34 (MB).

```

See peak memory touches near 40GB. You need such configuration to run gfx design.

**Comment by vijayank88** [comment]
> @AnikBalo With attached test case https://drive.google.com/file/d/1f-v3DRlYhyvd93hU1n7uEpONAmWhVBjw/view?usp=sharing itself able to run routing in my cloud server without any issues. Few updates you can do is increase your routing core number(You've mentioned 8 cores have currently). Update following in `config.mk`
> 
> ```
> export NUM_CORES='6'
> ```
> 
> See my logs: Running cloud server with 128GB RAM and 32 CORE machine.
> 
> ```
> [INFO DRT-0181] Start track assignment.
> [INFO DRT-0184] Done with 981779 vertical wires in 11 frboxes and 614195 horizontal wires in 11 frboxes.
> [INFO DRT-0186] Done with 207731 vertical wires in 11 frboxes and 165527 horizontal wires in 11 frboxes.
> [INFO DRT-0182] Complete track assignment.
> [INFO DRT-0267] cpu time = 00:05:11, elapsed time = 00:01:13, memory = 7168.23 (MB), peak = 10371.75 (MB)
> [INFO DRT-0187] Start routing data preparation.
> [INFO DRT-0267] cpu time = 00:00:03, elapsed time = 00:00:03, memory = 7432.49 (MB), peak = 10371.75 (MB)
> [INFO DRT-0194] Start detail routing.
> [INFO DRT-0195] Start 0th optimization iteration.
>     Completing 10% with 0 violations.
>     elapsed time = 00:01:44, memory = 24770.47 (MB).
>     Completing 20% with 38990 violations.
>     elapsed time = 00:03:54, memory = 39857.80 (MB).
>     Completing 30% with 49080 violations.
>     elapsed time = 00:04:26, memory = 39859.34 (MB).
> ```
> 
> See peak memory touches near 40GB. You need such configuration to run gfx design.

@AnikBalo 
I confirm that with shared test case able to complete routing without any violations. see log below:

```
[INFO DRT-0195] Start 57th optimization iteration.
    Completing 10% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 20% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 30% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 40% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 50% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 60% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 70% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 80% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 90% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
    Completing 100% with 0 violations.
    elapsed time = 00:00:00, memory = 43024.57 (MB).
[INFO DRT-0199]   Number of violations = 0.
[INFO DRT-0267] cpu time = 00:00:06, elapsed time = 00:00:00, memory = 43024.57 (MB), peak = 43818.77 (MB)
Total wire length = 22479719 um.
Total wire length on LAYER li1 = 0 um.
Total wire length on LAYER met1 = 8326739 um.
Total wire length on LAYER met2 = 9232035 um.
Total wire length on LAYER met3 = 2683827 um.
Total wire length on LAYER met4 = 2143809 um.
Total wire length on LAYER met5 = 93308 um.
Total number of vias = 1869664.
Up-via summary (total 1869664):.

--------------------------
 FR_MASTERSLICE          0
            li1     712233
           met1    1053658
           met2      79940
           met3      23218
           met4        615
--------------------------
                   1869664


[INFO DRT-0198] Complete detail routing.
Total wire length = 22479719 um.
Total wire length on LAYER li1 = 0 um.
Total wire length on LAYER met1 = 8326739 um.
Total wire length on LAYER met2 = 9232035 um.
Total wire length on LAYER met3 = 2683827 um.
Total wire length on LAYER met4 = 2143809 um.
Total wire length on LAYER met5 = 93308 um.
Total number of vias = 1869664.
Up-via summary (total 1869664):.

--------------------------
 FR_MASTERSLICE          0
            li1     712233
           met1    1053658
           met2      79940
           met3      23218
           met4        615
--------------------------
                   1869664


[INFO DRT-0267] cpu time = 14:53:59, elapsed time = 00:51:11, memory = 43024.57 (MB), peak = 43818.77 (MB)

[INFO DRT-0180] Post processing.
```
Its require 44GB Peak memory to run without any issue. Else you will see child killed signal always.

So there is no issue related tool.

**Comment by AnikBalo** [comment]
Ok thanks @vijayank88.

**Comment by AnikBalo** [comment]
Successfully Completed run with 44GB ram. Thanks a lot @vijayank88
