### ISSUE TITLE
problem in installing openroad

### ISSUE THREAD

**Issue by ripudamank2** [The-OpenROAD-Project/OpenROAD-flow-scripts#451]
-- Boost  found.
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  **Could NOT find Python3 (missing: Python3_LIBRARY Python3_INCLUDE_DIR
  Development)
Call Stack (most re**cent call first):
  /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.14/Modules/FindPython/Support.cmake:1170 (find_package_handle_standard_args)
  /usr/local/share/cmake-3.14/Modules/FindPython3.cmake:174 (include)
  src/CMakeLists.txt:135 (find_package)
  
  can you please help me solve this ?

**Comment by vvbandeira** [comment]
@ripudamank2 how are you trying to install OpenROAD? Are you using `build_openroad.sh --local`?
Also, did you follow the instructions [here](https://openroad.readthedocs.io/en/latest/user/GettingStarted.html#building-and-installing-the-software)?

**Comment by maliberty** [comment]
@ripudamank2 do you still need help?

**Comment by vvbandeira** [comment]
Closing as stale. Please re-open or file a new issue in case this is still relevant.
