### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by ashkanr65** [The-OpenROAD-Project/OpenROAD-flow-scripts#455]
Hi,When I try to make OpenROAD-flow-script I get this error:
user@ubuntu:~/OpenROAD-flow-scripts/flow$ make
[INFO][FLOW] Using platform directory ./platforms/nangate45
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
/bin/sh: 0: Illegal option -o pipefail
make: *** [Makefile:311: objects/nangate45/gcd/base/lib/NangateOpenCellLibrary_typical.lib] Error 2

My system is Ubuntu 20.04 running through VMware.
I am able to clone and verify installation:
git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
cd OpenROAD-flow-scripts
./build_openroad.sh --local
source ./setup_env.sh
yosys -help
openroad -help
exit

Is there any example I can follow?

**Comment by vvbandeira** [comment]
See https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/330 for how to fix the issue.
