### ISSUE TITLE
setting tcl include directory

### ISSUE THREAD

**Issue by dpsiddons** [The-OpenROAD-Project/OpenROAD-flow-scripts#468]
Op Ubuntu 22.04, building failes because it looks for /usr/include/tcl.h and friends, but it is all in /usr/include/tcl8.6/tcl.h etc. I'm guessing that this is defined somewhere globally, but I can't find where. It is possible, but extremely tedious to go through and find and edit all the relevant #include statements, but there must surely be a better way.

**Comment by maliberty** [comment]
I just upgraded to 22.04 and I see during cmake
-- TCL header: /usr/include/tcl/tcl.h

What do you see?

**Comment by dpsiddons** [comment]
Hi Matt,
   The programs all expected that, but in my installation, tcl.h is in /usr/lib/tcl8.6. I just realized that all of the offending code is in tools/OpenROAD, and its README.md gives a cmake parameter to set TCL_HEADER and TCL_LIBRARY. I'll try that and see if it fixes things. Is there a log of the cmake output?
Pete.

________________________________

**Comment by maliberty** [comment]
Do you have a non-standard install?  Why would a header be in /usr/lib?  I see
/usr/include/tcl/tcl.h  /usr/include/tcl8.6/tcl.h

**Comment by maliberty** [comment]
@vvbandeira would you test this in a fresh docker container to see what the issue is (if any)

**Comment by dpsiddons** [comment]
....Just to be clear, I built locally, using the "build_openroad.sh" script, so I didn't explicitly run cmake.
Pete.

________________________________

**Comment by dpsiddons** [comment]
I'm sorry, my mistake. I meant to type include not lib. My installation does not have /usr/include/tcl/tcl.h, only the 8.6 version. This was an upgrade from 20.04 to 22.04.
Pete.

________________________________

**Comment by vvbandeira** [comment]
@dpsiddons we just added support for ubuntu 22 on our DependecyInstaller script and we are able to build on a clean docker and VM running ubuntu 22. My suggestion would be to remove/purge the current install of tcl and re-install. Something along the lines of:

```
sudo apt purge tcl
sudo apt install tcl
```

**Comment by dpsiddons** [comment]
Hi Vitor,
   Thank you very much. I will give it a try.
Pete.

________________________________
