### ISSUE TITLE
Cannot run floorpan for ibex implementation

### ISSUE THREAD

**Issue by minghunghw** [The-OpenROAD-Project/OpenROAD-flow-scripts#469]
**Describe the bug**
I build the tool locally and can run the tutorial design successfully.
Then when I try to import my ibex implementation, it stuck at macro placement if manual macro cfg file is not given.
But it should run the automatic macro placement by default.
* [Toolname] stuck at macro placement (`mpl`)
* [Flow] 2_4_floorplan_macro
* [Design] ibex RISC-V system with sky130 sram

**Expected behavior**
Floorplan complete and run the flow to the end

**Screenshots**
```
(/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.' /home/kevinchen/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -exit -no_init  ./scripts/macro_place.tcl -metrics ./logs/sky130hd/pulpino/base/2_4_mplace.json) 2>&1 | tee ./logs/sky130hd/pulpino/base/2_4_mplace.log
OpenROAD v2.0-3729-g713ef39fc
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO MPL-0005] Found 16 macros.
[INFO MPL-0009] West pins 114.
[INFO MPL-0009] East pins 113.
[INFO MPL-0009] North pins 168.
[INFO MPL-0009] South pins 168.
^Cmake: *** [Makefile:441: results/sky130hd/pulpino/base/2_4_floorplan_macro.odb] Error 130
```

**Environment (please complete the following information):**

Please only report issues for supported OSs.

 - OS: CentOS 7
 - OpenROAD-flow commit: `1ba989a`

**File Uploads**
[Pulpino Testcase](https://github.com/minghungumich/Testcase/blob/main/floorplan_pulpino_sky130hd_base_2022-05-29_07-19.tar.gz)

**Additional context**

**Comment by minghunghw** [comment]
@mithro @msaligane I am facing floorpan issue when macro cfg is not provided.

**Comment by maliberty** [comment]
please use make <step>_issue to package your test case.

**Comment by vijayank88** [comment]
@minghungumich 
The right way to attach the test case for macro placement stage fail issue is,
`make macro_place_issue`

**Comment by minghunghw** [comment]
@vijayank88 The testcases is updated and I have confirmed I can reproduce the same log by running the provided shell script. [Macro Place Testcase](https://github.com/minghungumich/Testcase/blob/main/macro_place_pulpino_sky130hd_base_2022-05-30_14-58.tar.gz)

**Comment by vijayank88** [comment]
@maliberty 
Issue confirmed. Can you please have a look into that or please assign to right people?

**Comment by ravi-varadarajan** [comment]
@vijayank88  Vijayan What do I do to reproduce the issue locally. I see two tar files when I click on the link above? Do I need both?
thanks
-ravi

**Comment by minghunghw** [comment]
@ravi-varadarajan This one should be reproducible. [Macro Place Testcase](https://github.com/minghungumich/Testcase/blob/main/macro_place_pulpino_sky130hd_base_2022-05-30_14-58.tar.gz)

**Comment by vijayank88** [comment]
@ravi-varadarajan 
are you able to reproduce the issue with above `Macro Place Testcase`?

**Comment by ravi-varadarajan** [comment]
Apologies for the delay. I will investigate and get back on this

**Comment by vijayank88** [comment]
@minghungumich 
Is this issue still valid?
We're not finding the test case.

**Comment by minghunghw** [comment]
This is obsolete. I will close the issue.
