### ISSUE TITLE
PDN breaks after defining global connect for macro pg pins

### ISSUE THREAD

**Issue by minghunghw** [The-OpenROAD-Project/OpenROAD-flow-scripts#477]
**Describe the bug**
I build the tool locally and can run the tutorial design successfully.
Then when I try to import my ibex implementation, it stuck at macro placement if manual macro cfg file is not given.
But it should run the automatic macro placement by default.
* [Toolname] wrong functionality at pdngen (`pdn`)
* [Flow] 2_6_floorplan_pdn
* [Design] ibex RISC-V system with sky130 sram

**Expected behavior**
Power stripe and straps should not be destroyed. Only connect power stripe to sram power pins.

**Screenshots**
When using default `pdn.tcl`
![截圖 2022-06-06 00 35 51](https://user-images.githubusercontent.com/73398758/172060869-3a177b56-49ce-4a13-8fad-0643ae2b9f0c.png)
When using self defined `pdn.tcl`
(Only add the following api command before global_connect)
```
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^vccd1$}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^vssd1$}
```
![截圖 2022-06-06 00 36 29](https://user-images.githubusercontent.com/73398758/172060890-059b406d-b423-4654-9ec2-829dfeafb83b.png)

**Environment (please complete the following information):**

Please only report issues for supported OSs.

 - OS: CentOS 7
 - OpenROAD-flow commit: `1ba989a`

**File Uploads**
[PDN Testcase](https://github.com/minghungumich/Testcase/blob/main/pdn_pulpino_sky130hd_base_2022-06-05_16-30.tar.gz)

**Additional context**

**Comment by minghunghw** [comment]
@mithro @msaligane I am facing pdn issue when manual pdn cfg is defined.

**Comment by gadfort** [comment]
@minghungumich is the issue that there are no straps on met4 over the macro? That would be because PDNGEN will not add straps on layers that the macro has metal in (since the highest pins are in met4, the only metal that can connect is on met5).

**Comment by minghunghw** [comment]
@arlpetergadfort I know there are blockages in macro.lef so PDNGEN will not add the strap over it. I think the main issue is after I add extra global connect for macro pg pins, the connection should be a little difference with first figure (default setting). There are only vias and no straps in the second figure (manual setting). Maybe it is my klayout displaying error, but I did find there are lots of difference after adding global connect in DEF file. I use the default sky130hd pdn.tcl setting as shown below.
```
####################################
# global connections
####################################
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDD$} -power
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDDPE$}
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDDCE$}
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {VPWR}
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {VPB}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^VSS$} -ground
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^VSSE$}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {VGND}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {VNB}
global_connect
####################################
# voltage domains
####################################
set_voltage_domain -name {CORE} -power {VDD} -ground {VSS}
####################################
# standard cell grid
####################################
define_pdn_grid -name {grid} -voltage_domains {CORE}
add_pdn_stripe -grid {grid} -layer {met1} -width {0.48} -pitch {5.44} -offset {0} -followpins -extend_to_core_ring
add_pdn_stripe -grid {grid} -layer {met4} -width {1.600} -pitch {27.140} -offset {13.570} -extend_to_core_ring
add_pdn_stripe -grid {grid} -layer {met5} -width {1.600} -pitch {27.200} -offset {13.600} -extend_to_core_ring
add_pdn_ring -grid {grid} -layers {met4 met5} -widths 5.0 -spacings 2.0 -core_offsets 4.5
add_pdn_connect -grid {grid} -layers {met1 met4}
add_pdn_connect -grid {grid} -layers {met4 met5}
####################################
# macro grids
####################################
####################################
# grid for: CORE_macro_grid_1
####################################
define_pdn_grid -name {CORE_macro_grid_1} -voltage_domains {CORE} -macro -orient {R0 R180 MX MY} -halo {2.0 2.0 2.0 2.0} -default -grid_over_boundary
add_pdn_connect -grid {CORE_macro_grid_1} -layers {met4 met5}
####################################
# grid for: CORE_macro_grid_2
####################################
define_pdn_grid -name {CORE_macro_grid_2} -voltage_domains {CORE} -macro -orient {R90 R270 MXR90 MYR90} -halo {2.0 2.0 2.0 2.0} -default -grid_over_boundary
add_pdn_connect -grid {CORE_macro_grid_2} -layers {met4 met5}
```
And I add two global connection for macros.
```
add_global_connection -defer_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^vccd1$}
add_global_connection -defer_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^vssd1$}
```

**Comment by gadfort** [comment]
> @arlpetergadfort I know there are blockages in macro.lef so PDNGEN will not add the strap over it. I think the main issue is after I add extra global connect for macro pg pins, the connection should be a little difference with first figure (default setting). There are only vias and no straps in the second figure (manual setting). Maybe it is my klayout displaying error, but I did find there are lots of difference after adding global connect in DEF file. I use the default sky130hd pdn.tcl setting as shown below.

When I ran it, the straps were present after the pdn step (with the run script in the issue you uploaded). You may want to check the layout in OpenROAD to see when the straps disappear.

Global connect doesn't add or remove anything physical it just tells the database what net to connect to what pins.

**Comment by minghunghw** [comment]
@arlpetergadfort Could you share your screenshot with straps present? If that, this might be my klayout problem. Because as you said, it should make no difference with default setting.

**Comment by gadfort** [comment]
Here is the screenshot of the upper left corner.
![corner](https://user-images.githubusercontent.com/46405338/172078313-b98f4cdc-eb0e-4c76-b893-2bc9e239c249.png)

You can see the straps on met4 and met5. There are vias connected the memory to the nets on met5 (not visible in this image).

**Comment by minghunghw** [comment]
Thanks! It looks like my klayout displaying problem. I can see those straps in openroad gui.
