### ISSUE TITLE
A routing error of a large design

### ISSUE THREAD

**Issue by AyaseErii** [The-OpenROAD-Project/OpenROAD-flow-scripts#483]
**Describe the bug**
Hello, I tried to generate a GDSII for a larger custom design with OpenROAD. Everything went well from 1_yosys synthesis to 4_cts. However, the tool stuck at 5_route with the error (Error137) messages below:

    ==========================================================================
    check_antennas
    --------------------------------------------------------------------------
    [INFO ANT-0001] Found 0 pin violations.
    [INFO ANT-0002] Found 0 net violations in 436064 nets.
    [INFO FLW-0007] clock clk period 1.085200
    [WARNING FLW-0010] more than one clock found. Skipping sdc update.
    [INFO FLW-0011] Path endpoint count 100795
    Elapsed time: 17:24.56[h:]min:sec. CPU time: user 1039.88 sys 0.92 (99%). Peak memory: 2960168KB.
    (/usr/bin/time -f 'Elapsed time: %E[h:]min:sec. CPU time: user %U sys %S (%P). Peak memory: %MKB.' /home/jun/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -exit -no_init  ./scripts/detail_route.tcl -metrics ./logs/sky130hd/my_design/base/5_2_TritonRoute.json) 2>&1 | tee ./logs/sky130hd/my_design/base/5_2_TritonRoute.log
    OpenROAD v2.0-3976-g43350fce0 
    This program is licensed under the BSD-3 license. See the LICENSE file for details.
    Components of this program may be licensed under more restrictive licenses which must be honored.
    [INFO ORD-0030] Using 16 thread(s).
    [INFO DRT-0149] Reading tech and libs.
    
    Units:                1000
    Number of layers:     13
    Number of macros:     441
    Number of vias:       25
    Number of viarulegen: 25
    
    [INFO DRT-0150] Reading design.
    
    Design:                   my_design_top
    Die area:                 ( 0 0 ) ( 2691190 2691190 )
    Number of track patterns: 12
    Number of DEF vias:       4
    Number of components:     1119600
    Number of terminals:      196
    Number of snets:          2
    Number of nets:           436064
    
    [INFO DRT-0167] List of default vias:
      Layer mcon
        default via: L1M1_PR
      Layer via
        default via: M1M2_PR
      Layer via2
        default via: M2M3_PR
      Layer via3
        default via: M3M4_PR
      Layer via4
        default via: M4M5_PR
    [INFO DRT-0162] Library cell analysis.
    [INFO DRT-0163] Instance analysis.
      Complete 10000 instances.
      Complete 20000 instances.
      Complete 30000 instances.
      Complete 40000 instances.
      Complete 50000 instances.
      Complete 60000 instances.
      Complete 70000 instances.
      Complete 80000 instances.
      Complete 90000 instances.
      Complete 100000 instances.
      Complete 200000 instances.
      Complete 300000 instances.
      Complete 400000 instances.
      Complete 500000 instances.
      Complete 600000 instances.
      Complete 700000 instances.
      Complete 800000 instances.
      Complete 900000 instances.
      Complete 1000000 instances.
      Complete 1100000 instances.
    [INFO DRT-0164] Number of unique instances = 58.
    [INFO DRT-0168] Init region query.
    [INFO DRT-0018]   Complete 10000 insts.
    [INFO DRT-0018]   Complete 20000 insts.
    [INFO DRT-0018]   Complete 30000 insts.
    [INFO DRT-0018]   Complete 40000 insts.
    [INFO DRT-0018]   Complete 50000 insts.
    [INFO DRT-0018]   Complete 60000 insts.
    [INFO DRT-0018]   Complete 70000 insts.
    [INFO DRT-0018]   Complete 80000 insts.
    [INFO DRT-0018]   Complete 90000 insts.
    [INFO DRT-0019]   Complete 100000 insts.
    [INFO DRT-0019]   Complete 200000 insts.
    [INFO DRT-0019]   Complete 300000 insts.
    [INFO DRT-0019]   Complete 400000 insts.
    [INFO DRT-0019]   Complete 500000 insts.
    [INFO DRT-0019]   Complete 600000 insts.
    [INFO DRT-0019]   Complete 700000 insts.
    [INFO DRT-0019]   Complete 800000 insts.
    [INFO DRT-0019]   Complete 900000 insts.
    [INFO DRT-0019]   Complete 1000000 insts.
    [INFO DRT-0019]   Complete 1100000 insts.
    [INFO DRT-0024]   Complete FR_MASTERSLICE.
    [INFO DRT-0024]   Complete FR_VIA.
    [INFO DRT-0024]   Complete li1.
    [INFO DRT-0024]   Complete mcon.
    [INFO DRT-0024]   Complete met1.
    [INFO DRT-0024]   Complete via.
    [INFO DRT-0024]   Complete met2.
    [INFO DRT-0024]   Complete via2.
    [INFO DRT-0024]   Complete met3.
    [INFO DRT-0024]   Complete via3.
    [INFO DRT-0024]   Complete met4.
    [INFO DRT-0024]   Complete via4.
    [INFO DRT-0024]   Complete met5.
    [INFO DRT-0033] FR_MASTERSLICE shape region query size = 0.
    [INFO DRT-0033] FR_VIA shape region query size = 0.
    [INFO DRT-0033] li1 shape region query size = 11510594.
    [INFO DRT-0033] mcon shape region query size = 11824744.
    [INFO DRT-0033] met1 shape region query size = 3023159.
    [INFO DRT-0033] via shape region query size = 489060.
    [INFO DRT-0033] met2 shape region query size = 293535.
    [INFO DRT-0033] via2 shape region query size = 391248.
    [INFO DRT-0033] met3 shape region query size = 293533.
    [INFO DRT-0033] via3 shape region query size = 391248.
    [INFO DRT-0033] met4 shape region query size = 117513.
    [INFO DRT-0033] via4 shape region query size = 19503.
    [INFO DRT-0033] met5 shape region query size = 19700.
    [INFO DRT-0165] Start pin access.
    [INFO DRT-0076]   Complete 100 pins.
    [INFO DRT-0078]   Complete 122 pins.
    [INFO DRT-0081]   Complete 48 unique inst patterns.
    [INFO DRT-0082]   Complete 1000 groups.
    [INFO DRT-0082]   Complete 2000 groups.
    [INFO DRT-0082]   Complete 3000 groups.
    [INFO DRT-0082]   Complete 4000 groups.
    [INFO DRT-0082]   Complete 5000 groups.
    [INFO DRT-0082]   Complete 6000 groups.
    [INFO DRT-0082]   Complete 7000 groups.
    [INFO DRT-0082]   Complete 8000 groups.
    [INFO DRT-0082]   Complete 9000 groups.
    [INFO DRT-0083]   Complete 10000 groups.
    [INFO DRT-0083]   Complete 20000 groups.
    [INFO DRT-0083]   Complete 30000 groups.
    [INFO DRT-0083]   Complete 40000 groups.
    [INFO DRT-0083]   Complete 50000 groups.
    [INFO DRT-0083]   Complete 60000 groups.
    [INFO DRT-0083]   Complete 70000 groups.
    [INFO DRT-0083]   Complete 80000 groups.
    [INFO DRT-0083]   Complete 90000 groups.
    [INFO DRT-0083]   Complete 100000 groups.
    [INFO DRT-0083]   Complete 110000 groups.
    [INFO DRT-0083]   Complete 120000 groups.
    [INFO DRT-0083]   Complete 130000 groups.
    [INFO DRT-0083]   Complete 140000 groups.
    [INFO DRT-0083]   Complete 150000 groups.
    [INFO DRT-0083]   Complete 160000 groups.
    [INFO DRT-0083]   Complete 170000 groups.
    [INFO DRT-0083]   Complete 180000 groups.
    [INFO DRT-0083]   Complete 190000 groups.
    [INFO DRT-0083]   Complete 200000 groups.
    [INFO DRT-0083]   Complete 210000 groups.
    [INFO DRT-0083]   Complete 220000 groups.
    [INFO DRT-0083]   Complete 230000 groups.
    [INFO DRT-0084]   Complete 237796 groups.
    #scanned instances     = 1119600
    #unique  instances     = 58
    #stdCellGenAp          = 1471
    #stdCellValidPlanarAp  = 64
    #stdCellValidViaAp     = 897
    #stdCellPinNoAp        = 0
    #stdCellPinCnt         = 1198039
    #instTermValidViaApCnt = 0
    #macroGenAp            = 0
    #macroValidPlanarAp    = 0
    #macroValidViaAp       = 0
    #macroNoAp             = 0
    [INFO DRT-0166] Complete pin access.
    [INFO DRT-0267] cpu time = 00:02:16, elapsed time = 00:00:09, memory = 4780.19 (MB), peak = 5061.14 (MB)
    [INFO DRT-0151] Reading guide.
    [INFO DRT-0156] guideIn read 100000 guides.
    [INFO DRT-0156] guideIn read 200000 guides.
    [INFO DRT-0156] guideIn read 300000 guides.
    [INFO DRT-0156] guideIn read 400000 guides.
    [INFO DRT-0156] guideIn read 500000 guides.
    [INFO DRT-0156] guideIn read 600000 guides.
    [INFO DRT-0156] guideIn read 700000 guides.
    [INFO DRT-0156] guideIn read 800000 guides.
    [INFO DRT-0156] guideIn read 900000 guides.
    [INFO DRT-0157] guideIn read 1000000 guides.
    [INFO DRT-0157] guideIn read 2000000 guides.
    
    Number of guides:     2420894
    
    [INFO DRT-0169] Post process guides.
    [INFO DRT-0176] GCELLGRID X 0 DO 390 STEP 6900 ;
    [INFO DRT-0177] GCELLGRID Y 0 DO 390 STEP 6900 ;
    [INFO DRT-0026]   Complete 10000 origin guides.
    [INFO DRT-0026]   Complete 20000 origin guides.
    [INFO DRT-0026]   Complete 30000 origin guides.
    [INFO DRT-0026]   Complete 40000 origin guides.
    [INFO DRT-0026]   Complete 50000 origin guides.
    [INFO DRT-0026]   Complete 60000 origin guides.
    [INFO DRT-0026]   Complete 70000 origin guides.
    [INFO DRT-0026]   Complete 80000 origin guides.
    [INFO DRT-0026]   Complete 90000 origin guides.
    [INFO DRT-0027]   Complete 100000 origin guides.
    [INFO DRT-0027]   Complete 200000 origin guides.
    [INFO DRT-0027]   Complete 300000 origin guides.
    [INFO DRT-0027]   Complete 400000 origin guides.
    [INFO DRT-0027]   Complete 500000 origin guides.
    [INFO DRT-0027]   Complete 600000 origin guides.
    [INFO DRT-0027]   Complete 700000 origin guides.
    [INFO DRT-0027]   Complete 800000 origin guides.
    [INFO DRT-0027]   Complete 900000 origin guides.
    [INFO DRT-0027]   Complete 1000000 origin guides.
    [INFO DRT-0027]   Complete 1100000 origin guides.
    [INFO DRT-0027]   Complete 1200000 origin guides.
    [INFO DRT-0027]   Complete 1300000 origin guides.
    [INFO DRT-0027]   Complete 1400000 origin guides.
    [INFO DRT-0027]   Complete 1500000 origin guides.
    [INFO DRT-0027]   Complete 1600000 origin guides.
    [INFO DRT-0027]   Complete 1700000 origin guides.
    [INFO DRT-0027]   Complete 1800000 origin guides.
    [INFO DRT-0027]   Complete 1900000 origin guides.
    [INFO DRT-0027]   Complete 2000000 origin guides.
    [INFO DRT-0027]   Complete 2100000 origin guides.
    [INFO DRT-0027]   Complete 2200000 origin guides.
    [INFO DRT-0027]   Complete 2300000 origin guides.
    [INFO DRT-0027]   Complete 2400000 origin guides.
    [INFO DRT-0028]   Complete FR_MASTERSLICE.
    [INFO DRT-0028]   Complete FR_VIA.
    [INFO DRT-0028]   Complete li1.
    [INFO DRT-0028]   Complete mcon.
    [INFO DRT-0028]   Complete met1.
    [INFO DRT-0028]   Complete via.
    [INFO DRT-0028]   Complete met2.
    [INFO DRT-0028]   Complete via2.
    [INFO DRT-0028]   Complete met3.
    [INFO DRT-0028]   Complete via3.
    [INFO DRT-0028]   Complete met4.
    [INFO DRT-0028]   Complete via4.
    [INFO DRT-0028]   Complete met5.
      complete 10000 nets.
      complete 20000 nets.
      complete 30000 nets.
      complete 40000 nets.
      complete 50000 nets.
      complete 60000 nets.
      complete 70000 nets.
      complete 80000 nets.
      complete 90000 nets.
      complete 100000 nets.
      complete 200000 nets.
      complete 300000 nets.
    [INFO DRT-0178] Init guide query.
    [INFO DRT-0029]   Complete 10000 nets (guide).
    [INFO DRT-0029]   Complete 20000 nets (guide).
    [INFO DRT-0029]   Complete 30000 nets (guide).
    [INFO DRT-0029]   Complete 40000 nets (guide).
    [INFO DRT-0029]   Complete 50000 nets (guide).
    [INFO DRT-0029]   Complete 60000 nets (guide).
    [INFO DRT-0029]   Complete 70000 nets (guide).
    [INFO DRT-0029]   Complete 80000 nets (guide).
    [INFO DRT-0029]   Complete 90000 nets (guide).
    [INFO DRT-0030]   Complete 100000 nets (guide).
    [INFO DRT-0030]   Complete 200000 nets (guide).
    [INFO DRT-0030]   Complete 300000 nets (guide).
    [INFO DRT-0030]   Complete 400000 nets (guide).
    [INFO DRT-0035]   Complete FR_MASTERSLICE (guide).
    [INFO DRT-0035]   Complete FR_VIA (guide).
    [INFO DRT-0035]   Complete li1 (guide).
    [INFO DRT-0035]   Complete mcon (guide).
    [INFO DRT-0035]   Complete met1 (guide).
    [INFO DRT-0035]   Complete via (guide).
    [INFO DRT-0035]   Complete met2 (guide).
    [INFO DRT-0035]   Complete via2 (guide).
    [INFO DRT-0035]   Complete met3 (guide).
    [INFO DRT-0035]   Complete via3 (guide).
    [INFO DRT-0035]   Complete met4 (guide).
    [INFO DRT-0035]   Complete via4 (guide).
    [INFO DRT-0035]   Complete met5 (guide).
    [INFO DRT-0036] FR_MASTERSLICE guide region query size = 0.
    [INFO DRT-0036] FR_VIA guide region query size = 0.
    [INFO DRT-0036] li1 guide region query size = 880684.
    [INFO DRT-0036] mcon guide region query size = 0.
    [INFO DRT-0036] met1 guide region query size = 615113.
    [INFO DRT-0036] via guide region query size = 0.
    [INFO DRT-0036] met2 guide region query size = 347832.
    [INFO DRT-0036] via2 guide region query size = 0.
    [INFO DRT-0036] met3 guide region query size = 25553.
    [INFO DRT-0036] via3 guide region query size = 0.
    [INFO DRT-0036] met4 guide region query size = 8391.
    [INFO DRT-0036] via4 guide region query size = 0.
    [INFO DRT-0036] met5 guide region query size = 1.
    [INFO DRT-0179] Init gr pin query.
    [INFO DRT-0185] Post process initialize RPin region query.
    [INFO DRT-0181] Start track assignment.
    [INFO DRT-0184] Done with 1236907 vertical wires in 8 frboxes and 640667 horizontal wires in 8 frboxes.
    [INFO DRT-0186] Done with 182652 vertical wires in 8 frboxes and 167023 horizontal wires in 8 frboxes.
    [INFO DRT-0182] Complete track assignment.
    [INFO DRT-0267] cpu time = 00:02:44, elapsed time = 00:00:25, memory = 9807.75 (MB), peak = 9942.76 (MB)
    [INFO DRT-0187] Start routing data preparation.
    [INFO DRT-0267] cpu time = 00:00:00, elapsed time = 00:00:00, memory = 9807.75 (MB), peak = 9942.76 (MB)
    [INFO DRT-0194] Start detail routing.
    [INFO DRT-0195] Start 0th optimization iteration.
    Command terminated by signal 9
    Elapsed time: 1:46.13[h:]min:sec. CPU time: user 998.84 sys 10.45 (950%). Peak memory: 12510284KB.
    make: *** [Makefile:575: results/sky130hd/my_design/base/5_route.odb] Error 137

**Environment (please complete the following information):**
Please only report issues for supported OSs.
- OS: Ubuntu 20.04.3 LTS
- OpenROAD-flow latest

**Additional context**
The tool works with a relatively small custom design but cannot work with large design. Is there anything I missing? Could anyone help me with fixing this error issue? I will appreciate it!

**Comment by vijayank88** [comment]
@AyaseErii 
Run `make detail_routing_issue` in the `flow` directory and attach issue reproducible test case.

What's system RAM size?

**Comment by AyaseErii** [comment]
Thanks for the reply. I am trying to re-run the design to repo the log file with `make detail_routing_issue` now. 

The system RAM size is 16.0 GB (15.9 GB usable).

**Comment by AyaseErii** [comment]
I just tried the command you suggested `make detail_routing_issue` under the `flow`. It cannot work and show the error below:

    [INFO][FLOW] Using platform directory ./platforms/sky130hd
    make: *** No rule to make target 'detail_routing_issue'.  Stop.

**Comment by vijayank88** [comment]
try to increase swap space and try once.

@vvbandeira `terminated by signal 9` is out of memory kill right?

**Comment by vvbandeira** [comment]
@vijayank88 not always, but looks this is the case. DRT is using 9.8GB before iteration 0, this number tends to increase.

**Comment by AyaseErii** [comment]
Thanks for the explanation. I think it is a memory issue. I checked the the RAM and increased the swap space. Here is the info after increasing the swap space and using `sudo free -h` command to see if the space was increased:

                    total        used        free      shared  buff/cache   available
      Mem:           12Gi       1.0Gi        10Gi       0.0Ki       543Mi        11Gi
      Swap:          18Gi       1.0Gi        18Gi

PS: Here I really do not know why the total memory is 12G rather than 16G.

Then I tried the routing again, it can go to `5_2_TritonRoute` stage (the tool cannot go into step 5 at all before increasing the swap space) but still show the error indicating the memory:

    [INFO DRT-0036] met2 guide region query size = 347832.
    [INFO DRT-0036] via2 guide region query size = 0.
    [INFO DRT-0036] met3 guide region query size = 25553.
    [INFO DRT-0036] via3 guide region query size = 0.
    [INFO DRT-0036] met4 guide region query size = 8391.
    [INFO DRT-0036] via4 guide region query size = 0.
    [INFO DRT-0036] met5 guide region query size = 1.
    [INFO DRT-0179] Init gr pin query.
    [INFO DRT-0185] Post process initialize RPin region query.
    [INFO DRT-0181] Start track assignment.
    [INFO DRT-0184] Done with 1236907 vertical wires in 8 frboxes and 640667 horizontal wires in 8 frboxes.
    [INFO DRT-0186] Done with 182652 vertical wires in 8 frboxes and 167023 horizontal wires in 8 frboxes.
    [INFO DRT-0182] Complete track assignment.
    [INFO DRT-0267] cpu time = 00:02:49, elapsed time = 00:00:29, memory = 9797.41 (MB), peak = 10048.95 (MB)
    [INFO DRT-0187] Start routing data preparation.
    [INFO DRT-0267] cpu time = 00:00:00, elapsed time = 00:00:00, memory = 9797.41 (MB), peak = 10048.95 (MB)
    [INFO DRT-0194] Start detail routing.
    [INFO DRT-0195] Start 0th optimization iteration.
        Completing 10% with 0 violations.
        elapsed time = 00:01:13, memory = 11914.71 (MB).
    Command terminated by signal 9
    Elapsed time: 3:46.00[h:]min:sec. CPU time: user 2348.75 sys 36.22 (1055%). Peak memory: 12497756KB.

Do I need to add more memory to my local machine? Any suggestions?

Thanks!

**Comment by vijayank88** [comment]
@AyaseErii 
Yes need to increase your RAM.
Is that Docker or local installation?

**Comment by AyaseErii** [comment]
I see. That is local installation, not docker.

**Comment by vijayank88** [comment]
I don't understan why `make detail_routing_issue` not working to provide the test case.

Try with increased system resource.

**Comment by vvbandeira** [comment]
> PS: Here I really do not know why the total memory is 12G rather than 16G.

I have seen similar things if the system does not have a dedicated GPU, that memory can be allocated to the on-board graphics.

@AyaseErii can you share a reproducible testcase so we can try to run on our servers? Then we can be sure if it is a resource issue and how much you will need.

if you cannot share, I would suggest adding as much swap as you can and running again. Note that using swap will increase runtime.

**Comment by AyaseErii** [comment]
I am trying to use a server with a larger memory to re-do the same design. The tool is running now and it is in `cts` stage. I will let you guys know once the flow was done. Thanks!

**Comment by vijayank88** [comment]
@AyaseErii 
Is memory issue got fixed?

**Comment by AyaseErii** [comment]
@vijayank88 @vvbandeira 
Something unexpected happened on my server side. After I fixed all other issues on my server, the design is under optimization iteration now (it has gone through several iterations and is still working). I think it is a memory issue, and I believe it got fixed by increasing the physical memory. Thank you very much!

**Comment by vvbandeira** [comment]
That's great @AyaseErii, please let us know if the design finishes the flow without error with the increased memory so we can close the issue.

**Comment by AyaseErii** [comment]
Thank you very much for the help. The tool finished the design without error.
