### ISSUE TITLE
cannot run the global_route using latest version of OpenROAD

### ISSUE THREAD

**Issue by irakobi** [The-OpenROAD-Project/OpenROAD-flow-scripts#499]
**bug description**

I was running the flow using the docker with latest version of OpenROAD then on the stage of global_route I'm having the following stack which doesn't really describe the error. actually this flow has been working using the old version of OpenROAD generated in August 2021.

Using that version in fastroute logfile I was expecting to continue with processing the blockages and continue to the antenna checking and  generate the 5_1_route_gr.def until the flow end with final gds file.
```
 Macros: 0
[INFO GRT-0004] Blockages: 698
[INFO GRT-0019] Found 0 clock nets.
[INFO GRT-0001] Minimum degree: 2
[INFO GRT-0002] Maximum degree: 48
[INFO GRT-0017] Processing 4074 blockages on layer met1.
[INFO GRT-0017] Processing 14 blockages on layer met4.
[INFO GRT-0017] Processing 8 blockages on layer met5.
```
unfortunately using the latest version of OpenROAD it is being stack at this point as shown in the following attached log file. 

[5_1_fastroute.log](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/8995331/5_1_fastroute.log)

**Comment by maliberty** [comment]
Please attach a test case that reproduces the issue.

**Comment by irakobi** [comment]
> Please attach a test case that reproduces the issue.
[global_route.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/8995790/global_route.txt)

**Comment by irakobi** [comment]
> Please attach a test case that reproduces the issue.

@luis201420  here is the full folder of the testcase
[Temp-sense-gen Test case](https://github.com/irakobi/OpenFASOCtestcase/tree/master/openfasoc/generators/temp-sense-gen)

**Comment by kalabYibeltal** [comment]
> > Please attach a test case that reproduces the issue.
> 
> @luis201420 here is the full folder of the testcase [Temp-sense-gen Test case](https://github.com/irakobi/OpenFASOCtestcase/tree/master/openfasoc/generators/temp-sense-gen)

[temp-sense-gen.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/8996734/temp-sense-gen.tar.gz)
Temp-sensor-gen file tarred

**Comment by vijayank88** [comment]
@kalabYibeltal 
Test case missing `Error: global_route.tcl, 31 couldn't open "./blocks/sky130hd/tempsenseInst_custom_net.txt": no such file or directory`
Is that needed or comment and continue?

**Comment by kalabYibeltal** [comment]
It is needed. And the file exists in that directory.

**Comment by vijayank88** [comment]
@maliberty  @luis201420 
Issue confirmed. OpenROAD getting crashed while running `gloabl_route`

**Comment by vijayank88** [comment]
https://github.com/irakobi/OpenFASOCtestcase/blob/master/openfasoc/generators/temp-sense-gen/blocks/sky130hd/tempsenseInst_custom_net.txt

**Comment by luis201420** [comment]
The fix is on master branch now.
