### ISSUE TITLE
Unable to build OpenROAD-flow-scripts, missing yosys image

### ISSUE THREAD

**Issue by giumaug** [The-OpenROAD-Project/OpenROAD-flow-scripts#508]
I'm not able to build OpenROAD-flow-scripts image from master branch (commit 94eaf45a99e07bdd5b6e5a98c19d632216608bff).
The build exits in error because it is not able to find openroad/yosys:latest image on docker.io.

cd OpenROAD-flow-scripts/
[peppe@localhost OpenROAD-flow-scripts]$ podman build .
STEP 1/10: FROM openroad/flow-runtime
STEP 2/10: WORKDIR /OpenROAD-flow-scripts
--> Using cache fc988972c4ef8c1d95720fa68f9a048721807e987f8a053ab5f50be2340216f6
--> fc988972c4e
STEP 3/10: COPY --from=openroad/yosys /install ./tools/install/yosys
✔ docker.io/openroad/yosys:latest
Trying to pull docker.io/openroad/yosys:latest...
Error: COPY --from=openroad/yosys: no stage or image found with that name

**Comment by vijayank88** [comment]
@giumaug 
Do you followed installation instruction from here: https://openroad.readthedocs.io/en/latest/user/GettingStarted.html?

**Comment by giumaug** [comment]
Thanks for the reply. I apologize my fault. 
I tries to build from the dockerfile instead of using the build script. Initially the script didn't work out because my box has Podman instead of Docker.
After symlinking Docker to Podman I was able to build and run the container successfully.

**Comment by vijayank88** [comment]
@giumaug Can we consider its resolved?

**Comment by giumaug** [comment]
Yes, we can.

Il giorno mer 13 lug 2022 alle ore 14:50 vijayan ***@***.***>
ha scritto:
