### ISSUE TITLE
Issues building OpenROAD Locally

### ISSUE THREAD

**Issue by Bilel-Manai** [The-OpenROAD-Project/OpenROAD-flow-scripts#516]
Running ./build_openroad.sh --local results in issue during build and I am running ubuntu 22.04 as OS 
![build_issue_openroad](https://user-images.githubusercontent.com/65779814/179010375-ea0b072a-4ba1-496f-8f0f-9a3f2c63005d.PNG)

**Comment by maliberty** [comment]
Can you try a clean build?  Also please give the commit id you are building

**Comment by Bilel-Manai** [comment]
Hello,
Thank you for the response considering the commit id it's the latest (Openroad version :v2.0-4201-g89151c8ae) .What do you mean by a clean build I just cloned Openroad-flow-scripts and did a local build.

**Comment by Bilel-Manai** [comment]
I did try a clean build and it worked thank you very much
