### ISSUE TITLE
Error in building Openroad-flow-scripts locally

### ISSUE THREAD

**Issue by Bilel-Manai** [The-OpenROAD-Project/OpenROAD-flow-scripts#521]
Hi all I am trying to build Openroad-flow-scripts locally in a centos7 I get this error meanwhile I have installed it on both ubuntu 20.04 and 22.04 and never seen this error
![openroad](https://user-images.githubusercontent.com/65779814/179530793-78535972-eb34-4506-a5b2-4b7080044e43.PNG)

**Comment by vvbandeira** [comment]
What was the command you used to compile? Also, could you try with a clean workspace? This looks like the tools/install folder got deleted after you called the build script.

**Comment by Bilel-Manai** [comment]
I used ./build_openroad.sh --local and I  tried a clean build if that's what you meant by a clean workspace

**Comment by vvbandeira** [comment]
I am not sure what may be the issue here since we use Centos 7 for our CI and there all is working as expected. Maybe try to clone the repo again or check your bash setup.

**Comment by Bilel-Manai** [comment]
Okay thank you if I find something out I will let you know
