### ISSUE TITLE
PDN failes on an sram design

### ISSUE THREAD

**Issue by Bilel-Manai** [The-OpenROAD-Project/OpenROAD-flow-scripts#522]
Hi all , I am trying to use Openroad latest version on an Sram design there is the design rtl and the config file. 
[sram_v.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9134466/sram_v.txt)
[design_sdc.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9134467/design_sdc.txt)
[harness_mk.txt](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9134468/harness_mk.txt)
 
![image](https://user-images.githubusercontent.com/65779814/179580788-569868d6-74e4-4291-9734-c7392626bab7.png)

**Comment by maliberty** [comment]
Please package a test case at this step in the flow.  Usually the flow does so automatically on failure but if not please use https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/using_or_issue.md manually

**Comment by Bilel-Manai** [comment]
Hi 
Thank you for the answer , I can't seem to find the script I am supposed to run 
![image](https://user-images.githubusercontent.com/65779814/179583577-a3d45b90-974f-40ba-91cd-103a981aeef6.png)

**Comment by maliberty** [comment]
Sorry I looked to quickly and thought this was in openlane.  With ORFS just use "make pdn_issue" and upload the resulting tar file.

**Comment by Bilel-Manai** [comment]
[pdn_gcd_nangate45_base_2022-07-18_20-01.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9134621/pdn_gcd_nangate45_base_2022-07-18_20-01.tar.gz)
It's okay thank you for the help !!

**Comment by maliberty** [comment]
I ran your test case using the same commit and I get no error:
![image](https://user-images.githubusercontent.com/761514/179609402-988508af-0630-4cc7-9466-a3f2998f17f1.png)

Does running the packaged test fail for you?

**Comment by vvbandeira** [comment]
@Bilel-Manai, if you have a custom `config.mk` file you should run the command below. From the tar file, looks like you attached the issue for `nangate45/gcd` and not your sram design.

```
make pdn_issue DESIGN_CONFIG=<PATH_TO_config.mk>
```

**Comment by Bilel-Manai** [comment]
@vvbandeira yes you are right i did run it again for sram and there is the result and sorry for the confusion.

[pdn_sram_nangate45_base_2022-07-19_11-00.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9139917/pdn_sram_nangate45_base_2022-07-19_11-00.tar.gz)

**Comment by maliberty** [comment]
The block is only 11.99 microns wide:
![image](https://user-images.githubusercontent.com/761514/179763986-1774fa7f-5726-450e-8dde-d01b2485c2f1.png)

in the config it specifies
```
add_pdn_stripe -grid {grid} -layer {metal4} -width {0.48} -pitch {56.0} -offset {2}
```
The default spacing between stripes is half the pitch and so your block is too small to insert two stripes.  You could modify your spacing to make it work.  For example this works:
```
add_pdn_stripe -grid {grid} -layer {metal4} -width {0.48} -pitch {56.0} -offset {2} -spacing 1.5
add_pdn_stripe -grid {grid} -layer {metal7} -width {1.40} -pitch {40.0} -offset {2} -spacing 1.5
```
which produces
![image](https://user-images.githubusercontent.com/761514/179765329-a66c26a6-842b-4b6a-9974-d0b82e864682.png)

**Comment by Bilel-Manai** [comment]
I see thank you can you help me out with 1 more design it fails at this step and I did some testing and the problem is in 
set path_delay [sta::format_time [[[lindex [find_timing_paths -sort_by_slack] 0] path] arrival] 4] in the file OpenROAD-flow-scripts/flow/scripts/report_metrics.tcl not executing properly if you need a tar file for the testcase just tell me the command to make it Thank you once more !
![image](https://user-images.githubusercontent.com/65779814/179802068-0fece196-6e49-444a-87f7-3d531c22c5e9.png)

**Comment by maliberty** [comment]
The design you sent earlier had nothing in it but a few tapcells.  I guess the issue is that there is nothing to time in this design.  Where is your logic?

**Comment by Bilel-Manai** [comment]
there is the rtl i am running msbGeneric as my top module
[msbGeneric.tar.GZ](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9143153/msbGeneric.tar.GZ)

**Comment by maliberty** [comment]
Can't open it
```
tar ztf ~/Downloads/msbGeneric.tar.GZ

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by Bilel-Manai** [comment]
can you try and open this one Please 
[msbGeneric.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9143407/msbGeneric.tar.gz)

**Comment by maliberty** [comment]
you have no clock in your sdc

**Comment by Bilel-Manai** [comment]
silly me I didn't uncomment it but even when I did still same problem

**Comment by Bilel-Manai** [comment]
yeah you are right thank you !

**Comment by maliberty** [comment]
Glad to help.  Can this be closed?
