### ISSUE TITLE
Merging GDS/OAS file error

### ISSUE THREAD

**Issue by lulu9312** [The-OpenROAD-Project/OpenROAD-flow-scripts#550]
Describe the bug
Getting an error at GDS stage during merging GDS/OAS files. The additional files are present in the specified directory. Still it considers only one gds file.

Expected behavior
Should accept all the gds files present.

Screenshots
![gds3_error](https://user-images.githubusercontent.com/61928883/183032577-437def99-22c8-42a8-8941-c48bdd63f3ef.png)

**Comment by rovinski** [comment]
Please package a test case, it will help to resolve your issue much quicker.

However, all of the cells that are missing are not standard cells. Have you actually set the GDS files in `ADDITIONAL_GDS_FILES`?

**Comment by lulu9312** [comment]
@rovinski  Yes I have set the GDS files in ADDITIONAL_GDS_FILES. 
Screenshot 
![gds_error](https://user-images.githubusercontent.com/61928883/183060128-a76569ec-de01-4217-a67d-307b84f7c1db.png)
Here the export GDS command should take all .gds file gds but it considers only one. Here the standard cells are missing as well.

What do you mean pacakage a test case? Should I attach my config file here?

**Comment by vijayank88** [comment]
@lulu9312 
ORFS flow don't have built in `sky130_fd_sc_hvl` platforms. Check here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/tree/master/flow/platforms.
That's why its shows missing gds. Point  right path to `GDS_FILES`.

@vvbandeira why `hvl` library support missing from ORFS flow for sky130? OpenLane flow has support for `hvl` library.

**Comment by lulu9312** [comment]
@vijayank88 Yes I  have already added sky130hvl to the platforms. I have also pointed the right path.

![file_sky130hvl](https://user-images.githubusercontent.com/61928883/183238182-d39eeb57-bd5d-4275-b7c3-98c3176686cc.png)

**Comment by vijayank88** [comment]
@lulu9312 
Can you prefix with `ADDITIONAL_LEFS` `ADDITIONAL_GDS` `ADDITIONAL_LIBS`?

**Comment by lulu9312** [comment]
@vijayank88 I tried the above prefix  but no change.

**Comment by lulu9312** [comment]
@vijayank88 Got the error resolved by updating Klayout.

**Comment by lulu9312** [comment]
@vijayank88 Got the error resolved by updating Klayout

**Comment by msaligane** [comment]
which klayout version have you used? @lulu9312

**Comment by lulu9312** [comment]
@msaligane Right now I am on version 0.27.10 Previously, I was on version 0.26.2
