### ISSUE TITLE
Add check_setup opensta command to synthesis and final report scripts

### ISSUE THREAD

**Issue by tspyrou** [The-OpenROAD-Project/OpenROAD-flow-scripts#572]

**Comment by vijayank88** [comment]
@tspyrou 
`check_setup` command added part of `report_metrics`. For `final report` its already available here:
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/510b8a1771ecc6c2a7f65508d1753ba7794c4a01/flow/scripts/final_report.tcl#L61
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/510b8a1771ecc6c2a7f65508d1753ba7794c4a01/flow/scripts/report_metrics.tcl#L5

For synthesis stage am not able to add, but possible to add beginning of `floorplan` stage. Shall I add here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/510b8a1771ecc6c2a7f65508d1753ba7794c4a01/flow/scripts/floorplan.tcl#L3

**Comment by vijayank88** [comment]
@maliberty 
Any comment on this?

**Comment by maliberty** [comment]
I think floorplan is fine.  It gives us a sense of validity on the original inputs.

**Comment by vijayank88** [comment]
Ok thanks for the update. I'll create PR for the same with `check_setup` in floorplan stage.
