### ISSUE TITLE
cannot open openroad gui

### ISSUE THREAD

**Issue by sharkoo7** [The-OpenROAD-Project/OpenROAD-flow-scripts#599]
After running designs/sky130hd/chameleon, I wanted to view the result with openroad gui. But` make gui_final DESIGN_CONFIG=./designs/sky130hd/chameleon/config.mk` stucked at` loading spef`.  `make gui_floorplan DESIGN_CONFIG=./designs/sky130hd/chameleon/config.mk` didn't work as well. I wonder what's the problem?

**Comment by rovinski** [comment]
Please use the bug report template. It's there for a reason. Please state:
1. Your OpenROAD-flow-scrips version (git hash)
2. Your OS and version
3. How you are running it (natively or Docker)
4. Attach the full log

**Comment by sharkoo7** [comment]
1. c086c4689266038b03334d1198d1e0f0369df87d
2. Ubuntu 22.04.1 LTS
3. I am running it in docker
4. [log.zip](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/9681776/log.zip)
5.after completing the flow,` make gui_final DESIGN_CONFIG=./designs/sky130hd/chameleon/config.mk` stucked at` loading spef`.
![image](https://user-images.githubusercontent.com/113168256/193215575-ab40e495-81c4-41cf-b55e-b3bf779f5ffe.png)

**Comment by maliberty** [comment]
Would you try setting GUI_NO_TIMING=1 and see if the problem persists or not?  That will skip loading the spef.

**Comment by alybruin** [comment]
Hi @sharkoo7 .  I'm currently having the same issue with "make gui_final" stuck at "loading spef".  Did you ever resolve your issue and if yes, could you share your solution? Thank you very much in advance.

**Comment by maliberty** [comment]
@alybruin can you try my suggestion and report if it works?

**Comment by alybruin** [comment]
Hi @maliberty , yes I have tried your suggestion but still same issue with stuck at "loading spef".  In gui.tcl script, the GUI_NO_TIMING param is used to determine design_stage 1 - 6.  If design-stage = 6, it performs "Loading spef".  Else, it performs "Estimate parasitic".  Even when I commented out both loading spef and estimating parasitic, the GUI is still stuck and not opening.

**Comment by maliberty** [comment]
GUI_NO_TIMING will skip the loading or estimating of any parasitics.  If you have set it you should not get a "Loading spef" message at all.

So the problem is not related to parasitics.  How large is your design?

**Comment by maliberty** [comment]
Can you provide your .odb file?

**Comment by maliberty** [comment]
and the version of OR you are using (openroad -version)

**Comment by alybruin** [comment]
Hi @maliberty .  Sorry for not being clear earlier.  After setting GUI_NO_TIMING, I do not get "Loading spef" message anymore.  However, it's still not opening GUI, just stuck there.

**Comment by alybruin** [comment]
Hi @maliberty .  I'm running the example ethmac design using asap7 platform.  But same issue with gcd example design.

**Comment by maliberty** [comment]
@alybruin 
What version of OR?
What platform?
Are you using docker?

**Comment by alybruin** [comment]
@maliberty .  I'm running CentOS7 and using Docker.  As for OR version, I'm still trying to figure that out.  I'm using OR flow scripts, not OpenLane.  The way I tried to open GUI is in Docker, after make successful, I type "make gui-final".  Also, I can navigate to OpenROAD-flow-scripts/tools/install/OpenROAD/bin  and typing "./openroad -version" returns GITDIR-NOTFOUND and "./openroad -gui" returns Could not connect to any X display.

**Comment by maliberty** [comment]
I'm guessing this is a docker issue and not an OR issue.  In OL there is much discussion in https://github.com/The-OpenROAD-Project/OpenLane/issues/1149.  Would you try running docker with --privileged and see if that fixes it.

I can open that design in the gui with timing in <1m outside of docker.

**Comment by alybruin** [comment]
Hi @maliberty .  I did try adding that "DOCKER_OPTIONS += --privileged" but same issue.  Thank you for confirming that you can open GUI outside of Docker.  That may be a clue.

**Comment by maliberty** [comment]
You said that you are using ORFS so DOCKER_OPTIONS won't do anything as it is an OpenLane option.  How are you invoking docker in orfs?  You'll need to add the option there directly.

**Comment by alybruin** [comment]
To invoke Docker, I typed      "docker run --privileged -it -u $(id -u ${1000}):$(id -g ${1000}) -v $(pwd)/flow/platforms:/OpenROAD-flow-scripts/flow/platforms:ro openroad/flow-scripts"    With or without --privileged, same issue.   (For some reason the dollar sign not showing up in the Docker command.)

**Comment by maliberty** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/blob/ff85171cfb10dc44911db7a62cc2d86f03807756/Makefile#L34 shows all the options that OL uses.  I suspect you need to mount /tmp/.X11-unix too

**Comment by maliberty** [comment]
Did this work for you?

**Comment by alybruin** [comment]
Hi Matt.  I tried it while back when you first suggested but same issue.  So it didn't help.  I have put that issue aside for now and will come back to it in the future.  Thanks for all your help.

**Comment by zerzerzerz** [comment]
Hi, I encountered the same problem. I finally fix it by the following commands.
I am using `Docker` to build OpenROAD in `Ubuntu-18.04`.
When constructing the container from image, run these following commands. Because it needs GUI, so I choose `MobaXterm` via SSH to connect the remote server, which supports `x11-forwarding`. Then enter these commands to construct an container from the built image. If I specify the username and group when running the container, it failed with `cannot connect to display :10.0`. Maybe I need to configure more settings, but this method works for me. So I just run the container as `root`.
To set the `-e DISPLAY=:10.0`, I execute `echo $DISPLAY` in the terminal in remote server with x11-forwarding. The output is `localhost:10.0`, so I set `-e DISPLAY=:10.0`.
* Connect to remote server with MobaXterm (supporting x11-forwarding) via SSH
```bash
ssh -p <port> <username>@<ip_address>
```
* Check display device in remote server, and my output is `localhost:10.0`
```bash
echo $DISPLAY
```
* Construct and run the container from image, mount coresponding dirs with `-v` and set display with `-e DISPLAY=<YOUR_DISPLAY>`
```bash
docker run \
  -it \
  --privileged \
  -v $(pwd)/flow/platforms:/OpenROAD-flow-scripts/flow/platforms:ro \
  -v /etc/localtime:/etc/localtime \
  -v $HOME/.Xauthority:/root/.Xauthority \
  -e DISPLAY=:10.0 \
  --net=host \
  openroad/flow-scripts
```
* After executing these commands, just follow the official instructions to run
```bash
source setup_env.sh
openroad -gui
``` 
Finally I can use the GUI.
Hope this works for you~

**Comment by Amik-TJ** [comment]
> Hi, I encountered the same problem. I finally fix it by the following commands. I am using `Docker` to build OpenROAD in `Ubuntu-18.04`. When constructing the container from image, run these following commands. Because it needs GUI, so I choose `MobaXterm` via SSH to connect the remote server, which supports `x11-forwarding`. Then enter these commands to construct an container from the built image. If I specify the username and group when running the container, it failed with `cannot connect to display :10.0`. Maybe I need to configure more settings, but this method works for me. So I just run the container as `root`. To set the `-e DISPLAY=:10.0`, I execute `echo $DISPLAY` in the terminal in remote server with x11-forwarding. The output is `localhost:10.0`, so I set `-e DISPLAY=:10.0`.
> 
> * Connect to remote server with MobaXterm (supporting x11-forwarding) via SSH
> 
> ```shell
> ssh -p <port> <username>@<ip_address>
> ```
> 
> * Check display device in remote server, and my output is `localhost:10.0`
> 
> ```shell
> echo $DISPLAY
> ```
> 
> * Construct and run the container from image, mount coresponding dirs with `-v` and set display with `-e DISPLAY=<YOUR_DISPLAY>`
> 
> ```shell
> docker run \
>   -it \
>   --privileged \
>   -v $(pwd)/flow/platforms:/OpenROAD-flow-scripts/flow/platforms:ro \
>   -v /etc/localtime:/etc/localtime \
>   -v $HOME/.Xauthority:/root/.Xauthority \
>   -e DISPLAY=:10.0 \
>   --net=host \
>   openroad/flow-scripts
> ```
> 
> * After executing these commands, just follow the official instructions to run
> 
> ```shell
> source setup_env.sh
> openroad -gui
> ```
> 
> Finally I can use the GUI. Hope this works for you~

This worked for me. Thanks a lot

**Comment by maliberty** [comment]
You can use https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/util/docker_shell
