### ISSUE TITLE
Create build_openroad.sh log automatically

### ISSUE THREAD

**Issue by rovinski** [The-OpenROAD-Project/OpenROAD-flow-scripts#664]
**Is your feature request related to a problem? Please describe.**
Create a build log for `build_openroad.sh` automatically so that users don't have to follow extra steps when submitting build issues.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**Additional context**
We could use a solution similar to the one [here](https://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself).

**Comment by rovinski** [comment]
I can work on this when I get a chance or someone else can take over.

**Comment by vvbandeira** [comment]
@habibayassin can you propose a PR?

**Comment by habibayassin** [comment]
@vvbandeira yes sure
