### ISSUE TITLE
Export STA information

### ISSUE THREAD

**Issue by zerzerzerz** [The-OpenROAD-Project/OpenROAD-flow-scripts#689]
### Description

Thanks for your outstanding work! I want to know whether it exists a method to export the STA information like `.csv` format? Thanks!

**Comment by maliberty** [comment]
What do you mean by "STA information" exactly?  There is no .csv export currently but a lot of information is accessible through tcl.

**Comment by zerzerzerz** [comment]
After running `make gui_final`, I want to export the `Timing Report`, especially the `Data Path Details`. Thanks.

**Comment by zerzerzerz** [comment]
After opening the GUI, I cannot type anything in the tcl...
I can only use my mouse to click, but I cannot enter any tcl commands...
I am using docker in ubuntu-18.04

**Comment by maliberty** [comment]
I'm not aware of a way to dump out the timing paths in anything other than the ascii format report_checks uses.

@gadfort any thoughts on a dump from GUI?

@tspyrou is there any way to get a path as a tcl list like some tools provide?

**Comment by maliberty** [comment]
The GUI issue is a separate problem.  I've never seen that and have to assume it is something local to your X environment.

**Comment by zerzerzerz** [comment]
I can only click on the buttons on GUI, but cannot type any commands in the tcl section of GUI. Whether it exists other methods to interact with the OpenROAD, e.g., typing commands through bash terminal?

**Comment by zerzerzerz** [comment]
Oh I found that I can execute tcl commands throught writing tcl commands I want to execute in `./scripts/gui.tcl`. So if I want to get all `Dara Path Details`, which tcl command should I execute? Thanks!

**Comment by maliberty** [comment]
You don't need the gui - just run report_checks

**Comment by gadfort** [comment]
> I'm not aware of a way to dump out the timing paths in anything other than the ascii format report_checks uses.
> 
> @gadfort any thoughts on a dump from GUI?
> 
> @tspyrou is there any way to get a path as a tcl list like some tools provide?

I would think running report_checks and copying the output from the logger would be the best solution.

**Comment by zerzerzerz** [comment]
Can I use `report_checks` to export all path information? Since it can only dump one path.

**Comment by maliberty** [comment]
You can use -group_count <int>.  Please see the docs https://github.com/The-OpenROAD-Project/OpenSTA/blob/master/doc/OpenSTA.pdf for more info
