### ISSUE TITLE
Missing apostrophe in floorplan tcl

### ISSUE THREAD

**Issue by luarss** [The-OpenROAD-Project/OpenROAD-flow-scripts#698]
### Describe the bug

Minor bug, but I believe there is a missing apostrophe in scripts/floorplan.tcl, line 136. 

![image](https://user-images.githubusercontent.com/39641663/208392389-ca4b3057-599e-4ffc-9c2b-c00f30c7e8a3.png)

### Expected Behavior

See above.

### Environment

```shell
Error: floorplan.tcl, 143 extra characters after close-quote
Elapsed time: 0:05.38[h:]min:sec. CPU time: user 5.03 sys 0.31 (99%). Peak memory: 176012KB.
make: *** [results/nangate45/gcd/6/2_1_floorplan.odb] Error 1
```

### To Reproduce

Triggered the error when doing "make RESYNTH_AREA_RECOVER=1"

**Comment by vijayank88** [comment]
@luarss 
Yes its a bug from script. Missing double quote at the end in line 136.
