### ISSUE TITLE
ASAP7 has a single celler fill causing millions of instances to be created

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#732]
### Subject

[Stage]: asap7 platform PDK problem. Clearly visible in 4_2_cts_fillcell.log

### Describe the bug

ASAP7 only has a single filler cell defined. This causes millions of instances to be created, which again causes problems for the OpenROAD GUI.

Reporting takes a really long time since the OpenROAD GUI is slow. The OpenROAD GUI is run to during reporting stage to generate some images.

### Expected Behavior

Multiple filler cell sizes, so that so many instances doesn't have to be created.

### Environment

```shell
Git commit: d297c5b18d08684b550e74a3115d4c366bd92e01
kernel: Linux 5.19.0-26-generic
os: Ubuntu 22.10 (Kinetic Kudu)
cmake version 3.24.2
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Ubuntu clang version 15.0.2-1
```

### To Reproduce

Run asap7 design vs sky130hd, look at number of filler cells created. Many more filler cells in asap7.

Here is a design with a lot of filler cells to test with: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/725

### Relevant log output

```shell
From 4_2_cts_fillcell.log:

[INFO DPL-0001] Placed 9362608 filler instances.
```

**Comment by vijayank88** [comment]
There are two filler cells available in ASAP7.
```
FILLER_ASAP7_75t_R
FILLERxp5_ASAP7_75t_R
```
Tapcell list is:
```
TAPCELL_ASAP7_75t_R
TAPCELL_WITH_FILLER_ASAP7_75t_R
```
With `FILLERxp5_ASAP7_75t_R` logs for design `gcd`
```
[INFO DPL-0001] Placed 10268 filler instances.
```

By replacing `FILLER_ASAP7_75t_R` the logs as follows for design `gcd`
```
[INFO DPL-0001] Placed 3576 filler instances.
```

**Comment by oharboe** [comment]
@vijayank88 I tried:

```
export FILL_CELLS              = FILLER_ASAP7_75t_R FILLERxp5_ASAP7_75t_R
export TAP_CELL_NAME           = TAPCELL_ASAP7_75t_R TAPCELL_WITH_FILLER_ASAP7_75t_R
```

It didn't change the number of filler instances:

```
[INFO DPL-0001] Placed 9362608 filler instances.
```

**Comment by vijayank88** [comment]
Option 1: Add `export FILL_CELLS              = "FILLERxp5_ASAP7_75t_R"` in `designs/name/config.mk` and run the flow

Option 2: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/2b93d1f5f60a7e1fd2b55823379a1a485e865cec/flow/platforms/asap7/config.mk#L105 modify locally and run the flow.

**Comment by maliberty** [comment]
It would be better to add them at the platform level rather than for a specific design.  I was just holding off until we have a better set of cells.

**Comment by oharboe** [comment]
> It would be better to add them at the platform level rather than for a specific design. I was just holding off until we have a better set of cells.

Makes sense

**Comment by maliberty** [comment]
I looked at the design you linked to from this test.  It is 2mm on a side and only a few hundred gates.  It is 99.99+% empty space.  Are you trying to test a large number of objects in the GUI?  It isn't representative otherwise.

**Comment by oharboe** [comment]
> I looked at the design you linked to from this test. It is 2mm on a side and only a few hundred gates. It is 99.99+% empty space. Are you trying to test a large number of objects in the GUI? It isn't representative otherwise.

Yes: I eviscerated the design I was working on and this was all that was needed to bring the GUI to a crawl.

**Comment by oharboe** [comment]
Build times have improved enormously. From 118 minutes to 50 minutes for medium sized design, as an example. For bigger designs should show a bigger improvements.

I haven't tested the GUI yet.

**Comment by oharboe** [comment]
Gui works to. 

Thanks!
