### ISSUE TITLE
ASAP7 GDS appears to be partially shrunk 4x

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenROAD-flow-scripts#790]
### Subject

[Stage]: GDS generation.

### Describe the bug

I was looking at the ASAP7 GDS produced by ORFS and it looks a bit like the wires were shrunk 4x, but the standard cell contents were not.

M1:
![M1](https://user-images.githubusercontent.com/2029971/215060859-76251b5f-ead3-4e96-8ac9-b60cb5b53774.png)

M2:
![M2](https://user-images.githubusercontent.com/2029971/215060882-b0145885-a192-43fe-aaae-24c406d43043.png)

If I load the def into klayout, the M2 pitch looks good:

![M2-good](https://user-images.githubusercontent.com/2029971/215061787-2d06f957-d67f-424c-9d9d-13e0fd75b289.png)

If I look at the M2 pitch in the GDS, it's 1/4 size:

![M2-pitch](https://user-images.githubusercontent.com/2029971/215061852-e9deafb2-6b6a-4eca-90f8-cf5ec990dccc.png)

I'm not sure what is causing this, I immediately thought of the ASAP7 4x hack, but we are using the 1x lef.

An example of the issue: https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-Public/job/public_tests_all/job/master/594/artifact/flow/final_report_gcd_asap7_base_2023-01-25_15-42.tar.gz

### Expected Behavior

Correct sized GDS and no overlapping issues in M1/M2

### Environment

```shell
Git commit: 40bbbab3b1a446342a6341021a27a2a8b07d8d8f
os: Fedora Linux 37 (Workstation Edition)
cmake version 3.25.1
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
clang version 15.0.7 (Fedora 15.0.7-1.fc37)
```

### To Reproduce

Run any ASAP7 test in the CI

**Comment by maliberty** [comment]
That is really odd and I don't see an obvious explanation.   @rovinski any clues?

**Comment by antonblanchard** [comment]
The ASAP7 standard cell GDS libraries have `UNITS = 0.00025, 2.5e-10`, vs say the sky130hd ones which have `UNITS = 0.001, 1e-09`. That may have something to do with it.

**Comment by maliberty** [comment]
Thanks, that looks to be the key insight.
