### ISSUE TITLE
Make PDN config for mock-array-big design for ASAP7

### ISSUE THREAD

**Issue by yupferris** [The-OpenROAD-Project/OpenROAD-flow-scripts#815]
### Description

Looking at the `mock-array-big` design, we see that the power stripes don't line up between the inner macros and the top-level macro, as seen below for M5:

![image](https://user-images.githubusercontent.com/3166056/217831240-5baa8ea2-c6b3-4c14-ad21-b46da455a7d8.png)

### Suggested Solution

Other designs, such as `chameleon_hier`, have specific PDN config files for macros in the hierarchy. It would be useful to see a similar set of configs for the `mock-array-big` design.

### Additional Context

See additional relevant discussion here: https://github.com/The-OpenROAD-Project/OpenROAD/discussions/2868

**Comment by maliberty** [comment]
Based on the discussion is this still relevant?

**Comment by yupferris** [comment]
> Based on the discussion is this still relevant?

I don't think so.
