### ISSUE TITLE
Remove manual placement in design/asap7/mock-array-big and use MPL2

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#873]
### Description

Can MPL2 lay out an array of macros?

### Suggested Solution

Remove manual placement in design/asap7/mock-array-big and switch to mpl2

**Comment by maliberty** [comment]
The simplest is to try.  My guess is it won't be as perfect as doing it by yourself.

**Comment by oharboe** [comment]
> The simplest is to try. My guess is it won't be as perfect as doing it by yourself.

Is mpl2 enabled by default?

Can mpl2 be extended by algorithms or heuristics to be able to handle straightforward array cases?

**Comment by maliberty** [comment]
The goal is to swap over all test cases to mpl2 and retire mpl.  We aren't quite there yet.  

How would mpl2 know that is a "straightforward array case" from the netlist?

**Comment by oharboe** [comment]
> The goal is to swap over all test cases to mpl2 and retire mpl. We aren't quite there yet.
> 
> How would mpl2 know that is a "straightforward array case" from the netlist?

Look at the inputs and outputs and how they connect and create a model of "springs" and discover a minimization of "forces" or something?

**Comment by maliberty** [comment]
That is 'force directed placement' but it isn't really a way of discovering an array.  As a general approach mpl2 is better.   I suggest starting by trying it.

**Comment by oharboe** [comment]
@maliberty Lots of MPL2 work under way, so this github issue is covered by lots of other pull requests and other work in progress, and I think by now we know that this is not a "good first issue" :-)

**Comment by maliberty** [comment]
It is still a goal for mpl2 to handle mock-array
