### ISSUE TITLE
Install ORFS in Ubuntu18.04

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#874]
### Subject

[Build] for compilation-related issues.

### Describe the bug

While running `./etc/DependencyInstaller.sh` in Ubuntu18.04 getting following error message.
```
Package libtcl is a virtual package provided by:
  libtcl8.5 8.5.19-4
  libtcl8.6 8.6.8+dfsg-3
You should explicitly select one to install.

E: Package 'libtcl' has no installation candidate
```

### Expected Behavior

Complete dependency installer in Ubuntu18.04

### Environment

```shell
First time installation
```

### To Reproduce

First time installation

**Comment by vijayank88** [comment]
@vvbandeira  @habibayassin 
Do we have support for Ubuntu18.04 to install Dependency packages automatically?

**Comment by maliberty** [comment]
We test on Ubuntu 22.04 LTS which is the current LTS release.

**Comment by vvbandeira** [comment]
Ubuntu18.04 is over five years old, and there have been two LTS releases since. The user can manually install the required package, as it was suggested.

> Package libtcl is a virtual package provided by:
  libtcl8.5 8.5.19-4
  libtcl8.6 8.6.8+dfsg-3
**You should explicitly select one to install.**


```
sudo apt install -y libtcl8.6
```

**Comment by maliberty** [comment]
We do support 22.04 LTS but don't have the bandwidth for old releases.
