### ISSUE TITLE
Unconnected PDN node on net VDD

### ISSUE THREAD

**Issue by yupferris** [The-OpenROAD-Project/OpenROAD-flow-scripts#919]
### Subject

[Stage]: Other. Please describe below.

### Describe the bug

In https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/918, I'm attempting to clean up floorplanning setup for the `mock-array-big` example. In doing so, I either get DRC errors as power straps end up too close to macros, or, if I adjust the pdn config [as such](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/918/files#diff-27ac0f3dd04316cbe20c08153c07233c020eae57be8e3711d0f220e13af23463L16-R17) to align better with the macros, I get a bunch of `Unconnected PDN node on net VDD` errors, which I don't know how to fix.

### Expected Behavior

The flow completes successfully and generates GDSII.

### Environment

```shell
[WARNING] Your current OpenROAD version is outdated.
It is recommened to pull the latest changes.
If problem persists, file a github issue with the re-producible test case.
kernel: Linux 5.15.0-60-generic
os: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
cmake version 3.22.1
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenROAD version: v2.0-7229-gd76c80d8e
-- System name: Linux
-- Compiler: GNU 11.3.0
-- Build type: RELEASE
-- Install prefix: /usr/local
-- C++ Standard: 17
-- C++ Standard Required: ON
-- C++ Extensions: OFF
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test C_COMPILER_SUPPORTS__-Wall
-- Performing Test C_COMPILER_SUPPORTS__-Wall - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wall
-- Performing Test CXX_COMPILER_SUPPORTS__-Wall - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-array-bounds
-- Performing Test C_COMPILER_SUPPORTS__-Wno-array-bounds - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-array-bounds
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-array-bounds - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-nonnull
-- Performing Test C_COMPILER_SUPPORTS__-Wno-nonnull - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-nonnull
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-nonnull - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-maybe-uninitialized
-- Performing Test C_COMPILER_SUPPORTS__-Wno-maybe-uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-maybe-uninitialized
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-maybe-uninitialized - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format-overflow
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format-overflow - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format-overflow
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format-overflow - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-variable
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-variable - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-variable
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-variable - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-function
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-function - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-function
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-function - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-write-strings
-- Performing Test C_COMPILER_SUPPORTS__-Wno-write-strings - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-write-strings
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-write-strings - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-sign-compare
-- Performing Test C_COMPILER_SUPPORTS__-Wno-sign-compare - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-sign-compare
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-sign-compare - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-deprecated
-- Performing Test C_COMPILER_SUPPORTS__-Wno-deprecated - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-deprecated
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-deprecated - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-c++11-narrowing
-- Performing Test C_COMPILER_SUPPORTS__-Wno-c++11-narrowing - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-c++11-narrowing
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-c++11-narrowing - Failed
-- Performing Test C_COMPILER_SUPPORTS__-Wno-register
-- Performing Test C_COMPILER_SUPPORTS__-Wno-register - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-register
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-register - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format
-- Performing Test C_COMPILER_SUPPORTS__-Wno-format - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-format - Success
-- Performing Test C_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal
-- Performing Test C_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-reserved-user-defined-literal - Failed
-- Performing Test C_COMPILER_SUPPORTS__-fpermissive
-- Performing Test C_COMPILER_SUPPORTS__-fpermissive - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-fpermissive
-- Performing Test CXX_COMPILER_SUPPORTS__-fpermissive - Success
-- Performing Test C_COMPILER_SUPPORTS__-x
-- Performing Test C_COMPILER_SUPPORTS__-x - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__-x
-- Performing Test CXX_COMPILER_SUPPORTS__-x - Failed
-- Performing Test C_COMPILER_SUPPORTS__c++
-- Performing Test C_COMPILER_SUPPORTS__c++ - Failed
-- Performing Test CXX_COMPILER_SUPPORTS__c++
-- Performing Test CXX_COMPILER_SUPPORTS__c++ - Failed
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-but-set-variable
-- Performing Test C_COMPILER_SUPPORTS__-Wno-unused-but-set-variable - Success
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-but-set-variable
-- Performing Test CXX_COMPILER_SUPPORTS__-Wno-unused-but-set-variable - Success
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- TCL readline library: /usr/lib/x86_64-linux-gnu/libtclreadline.so
-- TCL readline header: /usr/include/x86_64-linux-gnu
-- Found SWIG: /usr/bin/swig4.0 (found suitable version "4.0.2", minimum required is "3.0")  
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0")  
-- boost: 1.80.0
-- Found Python3: /usr/include/python3.10 (found version "3.10.6") found components: Development Development.Module Development.Embed 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- spdlog: 1.8.1
-- Found BISON: /usr/bin/bison (found version "3.8.2") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen dot 
-- STA version: 2.4.0
-- STA git sha: 20805c83cf4817f6d2ca7867a52dac226515a21e
-- System name: Linux
-- Compiler: GNU 11.3.0
-- Build type: RELEASE
-- Build CXX_FLAGS: -O3 -DNDEBUG
-- Install prefix: /usr/local
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- TCL library: /usr/lib/x86_64-linux-gnu/libtcl.so
-- TCL header: /usr/include/tcl/tcl.h
-- SSTA: 0
-- STA executable: /home/jake/dev/work/OpenROAD-flow-scripts/tools/OpenROAD/src/sta/app/sta
-- GPU is not enabled
-- Found re2: /opt/or-tools/lib/cmake/re2/re2Config.cmake (found version "9.0.0") 
-- Found Clp: /opt/or-tools/lib/cmake/Clp/ClpConfig.cmake (found version "1.17.7") 
-- Found Cbc: /opt/or-tools/lib/cmake/Cbc/CbcConfig.cmake (found version "2.10.7") 
-- Found Eigen3: /usr/local/share/eigen3/cmake/Eigen3Config.cmake (found version "3.4.0") 
-- Found SCIP: /opt/or-tools/lib/cmake/scip/scip-config.cmake (found version "8.0.0") 
-- GUI is enabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0") found components: serialization 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find VTune (missing: VTune_LIBRARIES VTune_INCLUDE_DIRS) 
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found suitable version "1.80.0", minimum required is "1.78")  
-- Found Boost: /usr/local/lib/cmake/Boost-1.80.0/BoostConfig.cmake (found version "1.80.0") found components: serialization system thread 
-- TCL readline enabled
-- Tcl Extended disabled
-- Python3 enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.mgSzAQ17Hv
```

### To Reproduce

- Check out #918
- `cd flow`
- `make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk`

### Relevant log output

```shell
< many similar lines to those below >

[WARNING PSM-0038] Unconnected PDN node on net VDD at location (456.978um, 469.437um), layer: 6.
[WARNING PSM-0039] Unconnected instance ces_6_6 at location (456.978um, 469.437um) layer: 6.
[WARNING PSM-0038] Unconnected PDN node on net VDD at location (456.978um, 463.437um), layer: 5.
[WARNING PSM-0039] Unconnected instance ces_6_6 at location (456.978um, 463.437um) layer: 5.
[WARNING PSM-0038] Unconnected PDN node on net VDD at location (456.978um, 463.437um), layer: 6.
[WARNING PSM-0039] Unconnected instance ces_6_6 at location (456.978um, 463.437um) layer: 6.
[WARNING PSM-0038] Unconnected PDN node on net VDD at location (456.978um, 457.437um), layer: 5.
[WARNING PSM-0039] Unconnected instance ces_6_6 at location (456.978um, 457.437um) layer: 5.
[WARNING PSM-0038] Unconnected PDN node on net VDD at location (456.978um, 457.437um), layer: 6.
[WARNING PSM-0039] Unconnected instance ces_6_6 at location (456.978um, 457.437um) layer: 6.
[WARNING PSM-0038] message limit reached, this message will no longer print
[WARNING PSM-0039] message limit reached, this message will no longer print
[ERROR PSM-0078] IR drop setup failed.  Analysis can't proceed.
Error: final_report.tcl, 58 PSM-0078
Elapsed time: 0:59.33[h:]min:sec. CPU time: user 58.51 sys 0.74 (99%). Peak memory: 1708464KB.
make: *** [logs/asap7/mock-array-big/base/6_report.log] Error 1
```

**Comment by maliberty** [comment]
The DRC errors might relate to https://github.com/The-OpenROAD-Project/OpenROAD/pull/3064 

@gadfort do you have time to look at the pdn issue?

**Comment by gadfort** [comment]
> The DRC errors might relate to https://github.com/The-OpenROAD-Project/OpenROAD/pull/3064 
> 
> @gadfort do you have time to look at the pdn issue?

@maliberty later today possibly, but I don't see a reproducible test case attached.

**Comment by maliberty** [comment]
@gadfort just instructions to reproduce above in "To Reproduce".

@yupferris it is faster for developers if you package a standalone test case

**Comment by gadfort** [comment]
@maliberty was this resolved with the changes to PDN?

**Comment by maliberty** [comment]
I haven't checked yet.

**Comment by gadfort** [comment]
@maliberty I tried running it, but I didn't get any errors related to the PDN (assuming I ran the right thing). But the routing finished with 10 drc violations.

**Comment by yupferris** [comment]
I've rebased #918 onto latest master (cd35c86980400ab561605c7ec591857648d8f353) and get the same output as outlined above. I can look into generating a standalone test case.

**Comment by yupferris** [comment]
I've followed the instructions given while creating an issue to create a reproduction archive, with `ISSUE_TAG=unconnected_pdn_node` and `make final_report_issue` as I believe the errors above are generated when running that particular script, even though the issue is likely introduced in pdn: [final_report_unconnected_pdn_node.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/11063423/final_report_unconnected_pdn_node.tar.gz). In case it makes any difference, here's an archive created using `make pdn_issue` as well: [pdn_unconnected_pdn_node.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/files/11063431/pdn_unconnected_pdn_node.tar.gz).

Let me know if these are insufficient.

**Comment by yupferris** [comment]
Also, the flow does generate `flow/reports/asap7/mock-array-big/base/5_route_drc.rpt` and `flow/reports/asap7/mock-array-big/base/congestion.rpt`, but these files are empty, so I'm not aware of any DRC errors that are generated.

**Comment by gadfort** [comment]
Okay, so I ran it with the changes, so maybe the fixes fixed the power grid, but it is clearly making it hard for the router to converge. (I ran the test yesterday, and did not have time to look at the uploaded testcase)

**Comment by yupferris** [comment]
> Okay, so I ran it with the changes, so maybe the fixes fixed the power grid, but it is clearly making it hard for the router to converge. (I ran the test yesterday, and did not have time to look at the uploaded testcase)

I can also see that the design now spends much more time in DRT, but I have no idea why. Are there any tips/further information that can be provided as to why it's working so much harder? Maybe something I can do differently here?

The "Unconnected PDN node" errors are also a mystery to me. I don't know what I should be looking for or how to debug further.

**Comment by maliberty** [comment]
@gadfort I still see unconnected PDN nodes with the head of master.  I'll look at the router but pdn still needs help.

**Comment by maliberty** [comment]
@gadfort nothing is connecting the macro to the grid:

M5:
![image](https://user-images.githubusercontent.com/761514/227959192-84450845-0915-4484-bceb-e9d53ac940ba.png)

M6:
![image](https://user-images.githubusercontent.com/761514/227959309-b7268a8a-0529-4389-b480-060ff4f47eb4.png)

**Comment by gadfort** [comment]
Looks like M5 is blocked and M6 probably doesn't have room to get the straps in (or they are blocked), and M7 should be easy to connect through

**Comment by gadfort** [comment]
I'll try to take a closer look tonight

**Comment by maliberty** [comment]
@gadfort Thanks.  I wonder if you have thoughts on how the power grid should be constructed.  I believe the block and the top use the same pdn config.  I'm wondering if your prior experience suggests that we should do something differently.

**Comment by gadfort** [comment]
@maliberty I usually use a different one for blocks, since you might need to push the grid down to enable power grids later.
Here, it looks like you could juts use M5 as the top level in the block and then M6 will connect over and ensure connectivity.

https://github.com/siliconcompiler/zerosoc/blob/main/openroad/pdngen_core_only.tcl

https://github.com/siliconcompiler/zerosoc/blob/main/openroad/pdngen_top.tcl

**Comment by maliberty** [comment]
@gadfort have you had a chance to look at this?

**Comment by maliberty** [comment]
> https://github.com/siliconcompiler/zerosoc/blob/main/openroad/pdngen_core_only.tcl
> https://github.com/siliconcompiler/zerosoc/blob/main/openroad/pdngen_top.tcl

@gadfort these examples seem to be hard coded for sky130.  Is this correct?  Do you have asap7 equivalents?

**Comment by maliberty** [comment]
@gadfort In #933 I have a solution by having a separate pdn for the Element.  I'm still curious why pdn fails in this configuration (I'm guessing is the blockages).  The priority is lower though.

**Comment by yupferris** [comment]
In that case, I'll make a new branch/PR with the changes I want on top of #933 so we can move forward more easily, and we can keep #918 open for this issue.

**Comment by gadfort** [comment]
> @gadfort In #933 I have a solution by having a separate pdn for the Element. I'm still curious why pdn fails in this configuration (I'm guessing is the blockages). The priority is lower though.

@maliberty yes, the blockages prevent PDN from doing anything. If there were no blockages on m6 and pins were placed on m5, then PDN could have reached in and connected. Long term I would like to be able to do edge connections to macros (but that also wouldn't apply here.

**Comment by maliberty** [comment]
@gadfort would it have worked to extend the stripes to the edges so as to avoid the blockages?

**Comment by gadfort** [comment]
I don't think so, it's on my wishlist to make that work, but at the moment there's no code that would support that
