### ISSUE TITLE
make floorplan should fail if macros overlap

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#970]
### Description

Example of overlapping macros, `make floorplan` doesn't fail. This problem exists for manually and automatically placed macros.

I have seen an error message if you use more than 100% of the die area, but if some macros are tall and some wide, you can run out of space without using anything near 100% of the area. 

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/969

Note that the flow does eventually fail, but not with a very clear error message and also, when doing regression testing on floorplanning, it would be good to have the floorplan do the regression testing step as it is much than letting the flow run to completion.ot 

If the floorplan is not realistic, but the macros do not overlap, the flow will fail and the failure can be at many various and sundry places and for many reasons. The check if the macros overlap is an early quick check for a necessary, but not sufficient condition for the flow to succeed. The main purpose of the check is to make error messages more directly actionable and to reduce turnaround times on early iteration on the floorplan.

```
[NesterovSolve] Iter: 2230 overflow: 8.55011 HPWL: 22156304
[NesterovSolve] Iter: 2240 overflow: 8.51194 HPWL: 22156994
[NesterovSolve] Iter: 2250 overflow: 8.47407 HPWL: 22157309
[ERROR GPL-0305] RePlAce diverged at newStepLength.
Error: global_place_skip_io.tcl, 30 GPL-0305
Command exited with non-zero status 1
Elapsed time: 3:04.56[h:]min:sec. CPU time: user 184.43 sys 0.08 (99%). Peak memory: 241448KB.
make: *** [Makefile:494: results/asap7/mock-array-big/base/3_1_place_gp_skip_io.odb] Error 1
```

### Suggested Solution

Error message from `make floorplan` which macros overlap

**Comment by vijayank88** [comment]
@oharboe Is this still relevant?

**Comment by oharboe** [comment]
While I think this could help reduce confusion, this is no longer on our radar
