### ISSUE TITLE
Disk quota exceeded

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenROAD-flow-scripts#980]
### Subject

[Build] for compilation-related issues.

### Describe the bug

I am trying to install latest ORFS with Censtos 07 of cloud server.

I have cloned the repo and run `sudo ./setup.sh`. It fails with below error.
```
Installing collected packages: pytz, numpy, six, python-dateutil, pandas
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
	status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
	strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
	**kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
	strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
	strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
	clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
	ensure_dir(destdir)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
	os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
	mkdir(name, mode)
OSError: [Errno 122] Disk quota exceeded: '/home/vijayan/.local/lib/python3.6/site-packages/pandas/_libs/tslibs'
```

@vvbandeira @oharboe any suggestion why it fails?

`/home/vijayan` has `4.5T` free space.

### Expected Behavior

Pass `setup.sh` script

### Environment

```shell
[vijayan@vlsi09 OpenROAD]$ ./etc/Env.sh 
mkdir: cannot create directory ‘build’: Disk quota exceeded
```

### To Reproduce

`sudo ./setup.sh` in Centos07

**Comment by oharboe** [comment]
@vijayank88 What do you think this error means above? ```Disk quota exceeded```

**Comment by vijayank88** [comment]
Yes, it's about local disk allocated. I have informed to IT team about the error and waiting for the response.

Meanwhile am looking for arguments to install packages with custom location.

Is that possible with `setup.sh`?

**Comment by oharboe** [comment]
> Yes, it's about local disk allocated. I have informed to IT team about the error and waiting for the response.
> 
> Meanwhile am looking for arguments to install packages with custom location.
> 
> Is that possible with `setup.sh`?

I would say no, because setup.sh is just a script that invokes lower level install scripts. Read the script, it is trivial.

However, even if you invoke the lower level setup scripts, those scripts need to set up all sorts of packages into the OS, so even if you invoke the lower level install packages directly, it sounds like you don't have the access rights to install packages.

**Comment by vijayank88** [comment]
I do have `sudo` access.

Let me hear back from IT team. Thanks.

**Comment by vvbandeira** [comment]
@vijayank88 is this a GCP machine or a machine from Chipware? If it is from Chipware is possible that they have a limit per user which you might be exceeding. Run `du -hd0 /home/vijayan`, if it is a round number is likely this is the problem.

**Comment by vijayank88** [comment]
@vvbandeira 
It is a GCP machine
with `du -hd0 /home/vijayan` getting
```
4.8G  /home/vijayan
```

**Comment by vvbandeira** [comment]
> [vijayan@**vlsi09** OpenROAD]$ ./etc/Env.sh 

Which machine? I cannot find `vlsi09` in our GCP VM list. Are you sure you are running this in the correct machine?

**Comment by vijayank88** [comment]
@vvbandeira 
I have messaged you in Slack channel DM. Please check that.

**Comment by oharboe** [comment]
@vijayank88 Glad to see you are using the new setup procedure thought :-) It is intended to be a no decisions, no questions, no harm done to your machine setup procedure.

**Comment by vijayank88** [comment]
As per update from @vvbandeira , it is purely related to allocated disk space for the user. Hence closing this. Thanks @oharboe
