### ISSUE TITLE
google turns up stale documentation

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD-flow-scripts#981]
### Subject

[Documentation] for documentation errors.

### Describe the bug

This page is stale:

https://openroad.readthedocs.io/en/stable/user/GettingStarted.html

### Expected Behavior

Purge stale documentation from servers. Only latest docs and not stale docs published.

### Environment

```shell
Git commit: cd996709a935321742cfdb2323721fafb7d8219a
kernel: Linux 5.19.0-38-generic
os: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
cmake version 3.24.2
```

### To Reproduce

https://www.google.com/search?q=build+openroad&oq=build+openroad

**Comment by vvbandeira** [comment]
I have removed the `stable` version from the docs. Now it should return a `404` page and redirect to the main docs.
